### ISSUE TITLE
Sources of ideas for new problems

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#107]
Someone suggested looking at https://www.reddit.com/r/dailyprogrammer to get ideas for new problems.

https://twitter.com/yeion7/status/641438746366377985

**Comment by behrtam** [comment]
Old acm-icpc problems might also be an interesting source for the level intermdediate/hard. Like: http://cs.baylor.edu/~hamerly/icpc/qualifier_2013/final_problem_statements.pdf

**Comment by outkaj** [comment]
We could throw in a couple more [Project Euler] (https://projecteuler.net/) problems.

In addition, I also like the [Rosalind] (http://rosalind.info/problems/list-view/) problems I've done (building off the transcription problem that already exists).

**Comment by petertseng** [comment]
Thanks for discussing, everyone. These are good sources. I think people can feel free to add more as time goes on, even if this issue is closed. Say the word if there are actions to be taken (e.g. if there is a desire to recommend some sources of problems in our documentation).
