### ISSUE TITLE
New About Language Section

### ISSUE THREAD

**Issue by mixolidia** [exercism/x-common#110]
Hello @exercism/track-maintainers 

There is a new about section for tracks. Please add a description of your track language and suggest what would be the best uses for that language. 

This section will appear on [exercism.io](http://exercism.io/) language info pages \(http\://exercism.io/languages/[track name\]). Once a description is available in about for your language, it will appear under the header '[Language Name] About:' .

cc: @kytrinyx @sguermond

**Comment by kytrinyx** [comment]
@exercism/track-maintainers to expand a little bit on what @mixolidia was saying -- for a lot of people coming in to exercism, they're not necessarily familiar with the languages that are listed, and having an *about* section that describes what the language is typically used for, or the types of problems that the language is well-suited to solving might entice people to try a language out.

**Comment by mixolidia** [comment]
Thanks @kytrinyx!

**Comment by masters3d** [comment]
Where do we add the description? How long can it be? Can we reference other descriptions like so? 

"Swift is an alternative for the Objective-C language that employs contemporary programming language theory concepts and strives to present a simpler syntax. Swift introduces true named parameters and retains key Objective-C concepts, including protocols, closures and categories, often replacing former syntax with cleaner versions and allowing these concepts to be applied to other language structures, like enums." -  https://en.wikipedia.org/wiki/Swift_(programming_language)

**Comment by kytrinyx** [comment]
Oh, right. Excellent questions!

Yeah, referencing and linking to other descriptions seems like a good idea.

I don't think we have a length in mind, but probably a paragraph or two (max) would be good.

The description should go into a file named `ABOUT.md` in the `docs/` directory at the root of each language repository. Right now if the file is missing we're just returing an empty string and ignoring it on the language page.
