### ISSUE TITLE
bracket-push: Improve exercise description

### ISSUE THREAD

**Issue by behrtam** [exercism/x-common#127]
> Ensure that all the curly braces and square brackets are matched correctly, and nested correctly.

[bracket-push.md](https://github.com/exercism/x-common/blob/master/bracket-push.md)

Contrary to this description the [go test](https://github.com/exercism/xgo/blob/master/bracket-push/bracket-push_test.go) not only checks for *curly* and *square brackets* but for round brackets/parentheses. In Addition the [go implementation](https://github.com/exercism/xgo/blob/master/bracket-push/example.go#L67) also returns an error 'unknown bracket' if it discovers any character that is not one of the 3 types of brackets, even whites spaces.

While the *README* often is just a high level description of the problem and the test suite provides you with all the details, I think this makes it unnecessary hard to implement the exercises similarly through the different tracks.

... at least the README for *bracket-push* should mention if the input string will contain other characters and how to treat them.

**Comment by kytrinyx** [comment]
The best READMEs seem to leave a fair amount of ambiguity, allowing different languages to implement different things without being inconsistent with the spec.

Maybe we could change the README to say "brackets and braces", leaving the interpretation more open.

**Comment by behrtam** [comment]
It was not clear to me that a certain amount of ambiguity is desired. My expectation was that e.g. `brackets('{[ ]}')` should not raise an exception in one and pass in another track.

The approaches and coding styles are sometimes very different between various languages so maybe it makes sense not to lay everything down to the last detail. Didn't really think about that aspect.

**Comment by soniakeys** [comment]
If I understand, one issue is if it's fair for test programs to test three kinds of braces when the readme mentions only two.  I suppose someone could write some logic that only worked for two kinds of braces but not be easily adapted to three, then be frustrated to discover they must handle three.  I expect that's rare though, and Katrina's suggestion of making the readme a little less specific might help in those cases.

Another issue is differences between the implementation in the Go and Javascript tracks.  I think they currently have the same test cases and expect the same results, other than the Go API also having this error return.  None of the current test cases are considered errors though, so the interpretation (that non-brace content would be an error) of the Go example program doesn't seem relevant.  Solvers in the Go are not compelled to make the same interpretation and in fact are free to return nil (no error) in all cases.

**Comment by behrtam** [comment]
I was thinking the wrong way. If it would be a *normal* application I would make sure that the behaviour with other characters than brackets is tested. But here we actually win some freedom by not testing it because every user can decide independently how to handle it.

Nonetheless I like Katrina's suggestion to say "brackets and braces" even though its only a very small change.

**Comment by kytrinyx** [comment]
Thanks for helping clarify.
