### ISSUE TITLE
The "word-count" readme references the golang tour in the elixir version (and possible other languages without a source)

### ISSUE THREAD

**Issue by mauromorales** [exercism/x-common#132]
When running the elixir word-count example I get a reference to the golang tour which seems to come from `x-common/word-count.yml`. I think this is misleading. In case there is no source it would be better not to present this section rather than a link to another language.

**Comment by behrtam** [comment]
In principle I don't know why a source for an exercise can't be language specific. I think it's good practice to provide references. But for a classic and simple exercise like `word-count` there is no real need for a source or at least no language specific one.

**Comment by kytrinyx** [comment]
The source for an exercise doesn't mean where the actual test suite came from--we make up all the READMEs and test suites. It's the inspiration.

With the word count example, I was inspired by the exercise on the go tour. It's a classic, but I happened to come across it there first. I don't know that it's necessary to give credit, but I feel like there's no harm in doing so.

**Comment by mauromorales** [comment]
@kytrinyx oh I see how that ended up there now ^__^ ... at the same time it is very confusing that if you go to the source_url you don't see anything related to the word count example.

**Comment by kytrinyx** [comment]
Ah, now that's a different problem :) They redid the entire tour since then. I'll fix it. Thanks!

**Comment by mauromorales** [comment]
@kytrinyx thank you for all the work behind exercism, I'm having lot's of fun and learning a lot with it :)

**Comment by kytrinyx** [comment]
It's a pleasure. Thanks for bringing things like this up. A lot of the decisions made early on don't necessarily make sense any more, and so it's good to question everything if it seems odd or surprising.
