### ISSUE TITLE
Contributing Guide: Porting an exercise to a new track.

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#137]
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-a-another-language-track

Write about how to port an exercise to a language.

**Comment by nickborromeo** [comment]
@kytrinyx Is this already fixed? I see that https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track already has content.

**Comment by kytrinyx** [comment]
Yeah, it looks like this got fleshed out. It used to be just "TODO: write this" or something like that. Thank you so much for helping triage all these old issues—it's such a huge help.

**Comment by nickborromeo** [comment]
Can we close this issue out? 😄

**Comment by celavek** [comment]
I'm confused by the following:
"Check out a branch for your the exercise"

I do not think the branches are already pre-created so that line should rather say
"Create a branch for the new exercise"

**Comment by nickborromeo** [comment]
@celavek i think what you are suggesting makes sense. Just my two cents, I think the wording that was chosen was because almost all the time (at least for me) I use `git checkout -b <branch_name>` to create and check out the branch.

**Comment by kytrinyx** [comment]
How about _check out a new branch for the exercise_?

**Comment by kytrinyx** [comment]
Oh. But this issue is definitely fixed, that's a minor detail.

Thanks for helping out with the triage, @nickborromeo—it's a bit overwhelming how many of these things get left hanging.
