### ISSUE TITLE
Contributing Guide: Write about how to extract shared inputs/outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#139]
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data

**Comment by kytrinyx** [comment]
I ended up merging the first draft of the contributing guide with some TODOs in it, so that different people can claim different sections, if they're feeling up to it.

@mikeyjcat you mentioned that you might grab this one when you have time.

**Comment by petertseng** [comment]
This has been completed via #400 - please see #230 for some discussion related to this issue, as #230 at some point became a duplicate of this issue.
