### ISSUE TITLE
Find tracks that implement a particular exercise?

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/x-common#160]
I find it useful to look at existing implementations of an exercise when adding a problem to a track. This is particularly useful for exercises without a .json file of tests and/or exercises where the description isn't particularly clear as to the author's intent.

Given this, is there an easy way to determine which tracks implement a particular problem? Right now I just peruse the couple of tracks that I know are most popular (and hence most likely to have a wide array of exercises).

**Comment by kytrinyx** [comment]
It's here: `http://x.exercism.io/problems/:slug`, e.g. http://x.exercism.io/problems/leap

**Comment by ryanplusplus** [comment]
Perfect, thanks!
