### ISSUE TITLE
largest-series-product: add common data?

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#164]
I feel like this problem is a pretty good candidate for having common test data.

Well, I'm sure a lot of other problems are too, but this one in particular caught my attention when reviewing code.

Things to think about:
* Any invalid inputs? `largest_series_product("1234a5", 2)`? `largest_series_product("12345", -1)`?
* I'd really like tests for `largest_series_product("123", 0)` (should return 1 for empty product) and `largest_series_product("", 1)` (should error). Currently most tracks only test `largest_series_product("", 0) == 1` which is reasonable since it's a boundary case, but in a two-input function isn't it right to test cases where only one input is a boundary as well as both?
* I'd really like a test for `largest_series_product("99099", 3)` - this should be 0 (but some people's code say 1 because they assume the minimum is 1... it's not!)
* Different languages handle error cases differently, be careful. Example: Ruby raise exceptions, Go return `(int, error)`, Clojure [just... doesn't](https://github.com/exercism/xclojure/blob/master/largest-series-product/largest_series_product_test.clj#L21)? (I feel like this should change...). But this is a problem for each track to handle individually.
* Obviously making each track actually use the common data is a bigger question, but that's a problem for each track to handle individually - let's at least get the process started by *having* common data.

tracks with this problem: http://x.exercism.io/problems/largest-series-product

I have an intent to do this myself, but I can't do it immediately so this issue will serve as a reminder for me when I can.

I'll survey the test data being used by the various tracks in a bit and see if I see any interesting features as well.

**Comment by kytrinyx** [comment]
Yes, definitely! Eventually I'd like to have common data for all the problems that are used in multiple tracks. I made a bunch of individual issues for it over in the "todo" repository (which is used for hackdays and things like 24pullrequests where a bunch of people are new to exercism and new to open source).

- https://github.com/exercism/todo/labels/shared-test-data
- https://github.com/exercism/todo/issues/104

**Comment by petertseng** [comment]
starting work on this.
