### ISSUE TITLE
Is there a way to specify a pattern for test files?

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/x-common#179]
The test framework we're using in Lua expects test files to include "_spec" in the name, but exercism seems to expect test files to include "_test". This mismatch causes exercism to fail to pull up test files from Lua exercises when the "Test Suite" button is clicked when viewing an exercise.

We can include configuration in each exercise that instructs the test framework to look for files named with "_test" instead of "_spec", but since that means maintaining a bunch of duplicate configurations I'm hoping to avoid that.

Is there an existing mechanism for indicating to exercism which files should be considered part of the test suite? If not, is this something worth adding? If someone can point me to the right place I'd be happy to take a crack at it.

**Comment by kytrinyx** [comment]
Yepp, add a key named `"test_pattern"` in the config.json at the root of the track. It's used as a regexp. See the javascript track: https://github.com/exercism/xjavascript/blob/master/config.json#L6

**Comment by ryanplusplus** [comment]
Excellent, thanks!
