### ISSUE TITLE
Duplicate Hamming distance exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/x-common#184]
While add exercises to the C# track, I found that the default list includes both the [hamming](hamming.md) and the [point-mutations](point-mutations.md) exercises. However, upon closer inspection, I believe these two exercises are duplicates. Shouldn't one of the two be removed/deprecated?

**Comment by kytrinyx** [comment]
point-mutations is deprecated.

**Comment by kytrinyx** [comment]
I'll something to the README to that effect.

**Comment by kytrinyx** [comment]
The following tracks should replace point-mutations with hamming:

```
{
	problem: {
		slug: "point-mutations",
		blurb: "Write a program that can calculate the Hamming difference between two DNA strands.",
		source: "The Calculating Point Mutations problem at Rosalind",
		source_url: "http://rosalind.info/problems/hamm/",
		track_ids: [
			"clojure",
			"elisp",
			"elixir",
			"erlang",
			"haskell",
			"lfe",
			"lisp",
			"ocaml",
			"rust",
			"scheme"
		]
	}
}
```

**Comment by NobbZ** [comment]
Will you post an issue at the corresponding tracks?

Katrina Owen <notifications@github.com> schrieb am So., 21. Feb. 2016 20:14:

**Comment by kytrinyx** [comment]
Yeah, on it.

**Comment by kytrinyx** [comment]
I forgot to add a link to this issue in the issues for each of the tracks. When this list is empty, then we can close the issue: http://x.exercism.io/problems/point-mutations

**Comment by NobbZ** [comment]
It seems as if there is no implementor left in the list of http://x.exercism.io/problems/point-mutations.

Can we close?
