### ISSUE TITLE
Add a CI verification step for metadata filenames

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#187]
For each individual file basename we should have both `.md` and `.yml` and optionally `.json`.

Something blew up because we had a file that said `yaml` instead of `yml`. Technically I think `yaml` is the correct file extension, so maybe we should rename everything and make the check be for `yaml` and `md`, but that's a separate problem.

**Comment by petertseng** [comment]
Funnily enough, this has been superseded by #457, and then closed by #458.
