### ISSUE TITLE
Fix confusion in Largest Series Product exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#197]
See exercism/ruby#262 and exercism/ruby#244

The README for the exercise uses the term _consecutive_ in a way that is ambiguous. In this context it means _consecutive by position_, not _consecutive by numerical sequence_.

To fix this we should:

- [x] update the README to clarify that the digits need to be consecutive by position, not necessarily in numeric order (e.g. '487' has the consecutive numbers '48', '487', and '87', even though 4 and 8 or 8 and 7 are not considered _consecutive numbers_.) It would help to not use _0123456789_ as the example.
- [x] create a set of shared test data (`largest-series-product.json`)
- [ ] survey the existing language tracks that implement this exercise to see that they're correctly implemented against the requirements as defined above.

At the moment the existing implementations are as follows:

- [ ] https://github.com/exercism/xclojure/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xcsharp/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xecmascript/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xelixir/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xerlang/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xgo/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xjavascript/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xlfe/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xlua/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xpython/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xruby/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xscala/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xswift/tree/master/exercises/largest-series-product
- [ ] https://github.com/exercism/xhaskell/tree/master/largest-series-product
- [ ] https://github.com/exercism/xperl5/tree/master/largest-series-product

**Comment by neontapir** [comment]
Thanks. I've been traveling on business and couldn't file this right away.

**Comment by petertseng** [comment]
I wil update READMEs, but have my hands full with other tasks right now so I can't get to the other two items, so they are free for others to take!

**Comment by petertseng** [comment]
Oh wait, we already have common test data thanks to #167 , I forgot. So that means the only thing left to do is to ensure that all languages have the correct interpretation of "consecutive". My previous statement stands (this task is open for others to take!)

**Comment by kytrinyx** [comment]
I'll submit an issue per track (using github.com/exercism/blazon) that explains what we want to verify.

**Comment by kytrinyx** [comment]
Issues submitted:

* https://github.com/exercism/xclojure/issues/106
* https://github.com/exercism/xcsharp/issues/64
* https://github.com/exercism/xecmascript/issues/204
* https://github.com/exercism/xelixir/issues/146
* https://github.com/exercism/xerlang/issues/91
* https://github.com/exercism/xgo/issues/258
* https://github.com/exercism/xhaskell/issues/99
* https://github.com/exercism/xjavascript/issues/171
* https://github.com/exercism/xlfe/issues/24
* https://github.com/exercism/xlua/issues/130
* https://github.com/exercism/xperl5/issues/109
* https://github.com/exercism/xpython/issues/317
* https://github.com/exercism/xruby/issues/264
* https://github.com/exercism/xscala/issues/106
* https://github.com/exercism/xswift/issues/122

I'm going to close this issue since we don't need the double-bookkeeping.
