### ISSUE TITLE
Profile Page: completed exercises chart

### ISSUE THREAD

**Issue by masters3d** [exercism/x-common#218]
I love the profile page but I am not a fan of the percentage of completion as the first thing that gets seen. 
Humans are kinna of prideful creatures. A profile is something I'd like to show my friends when we are having coffee. 
The percentage of completion makes it feel to me that I have not *finished* something or that I am falling. 
I much rather have a page that shows me *how many * problems I've completed and maybe if I click or hover over the language I can get a percentage but the percentage should not be the first thing I see when go to my page. 

![image](https://cloud.githubusercontent.com/assets/6539412/14324872/94ba0a38-fbdb-11e5-95ce-30b469b4fa5b.png)

Perhaps it can be something like this and also include how many problems I have nitpicked from each language? 

// Something along these lines
Swift
35 Completed Problems 
45 Peer Reviewed Problems
![image](https://cloud.githubusercontent.com/assets/6539412/14325034/465a809c-fbdc-11e5-93d8-8a89299b117b.png)

**Comment by kytrinyx** [comment]
Yeah, I'm all for making a change like this, both in terms of moving or downplaying the progress bars, as well as including how many problems the person has reviewed.

Let's do the thing where we show you the icon + completed problems + peer reviewed problems, and then if you hover over it (or click?) you get more information.

I'm not married to the progress bar, it's an experiment in giving more information. If a grid of the language icons with numbers gives a better impression, we can drop the progress bars altogether.

**Comment by kytrinyx** [comment]
@masters3d I just realized that this ended up in the x-common repository. Would you mind reopening it in https://github.com/exercism/exercism.io/issues ?

**Comment by kytrinyx** [comment]
Sweet, thanks!
