### ISSUE TITLE
pangram: missing edge case

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#222]
@helenst came across a solution that had a bug that the test suite didn't catch. It's addressed in https://github.com/exercism/xpython/pull/331

The solution worked by accident because 'the quick...' happens to be alphabetically greater than 'abcdef...'.

Here's the test case that was added:

```
def test_invalid_pangram(self):
    self.assertFalse(
        is_pangram('the quick brown fish jumps over the lazy dog'))
```

We need to:
- [x] update the canonical data - https://github.com/exercism/x-common/blob/master/pangram.json
- [x] draft a detailed issue
  - [x] describes the problem that was found
  - [x] describes the fix
  - [x] links to the canonical data (and mentions that it has been updated with the new test cases)
  - [x] suggests that the exercise should be fixed to include these test cases
  - [x] links to this specific issue (so we get a visual todo list)
- [x] submit the issue to the relevant tracks using [blazon](https://github.com/exercism/blazon)

**Comment by kytrinyx** [comment]
I'm reopening this, since we haven't put together the issue text to be blasted across all the relevant repositories with blazon.

**Comment by IanWhitney** [comment]
Yay for Blazon.

**Comment by kotp** [comment]
exercism/x-common#284 hopefully helps clarifies this.

**Comment by behrtam** [comment]
All tracks have incorporated the change, even the java track have merged the change they just didn't close the issue. So we could close this here, right?
