### ISSUE TITLE
Assemble exercise README including the docs/TESTS.md?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#229]
At the moment the README for each exercise is assembled using:
- the name of the exercise (wordified from the problem slug)
- the blurb (from the YAML file in x-common)
- the description (from the Markdown file in x-common)
- the language-track SETUP.md file
- the exercise-specific HINTS.md file

The `docs/TESTS.md` often contains excellent and relevant information about how to run the tests. Should we include that in addition to the SETUP.md file (and only have something in SETUP.md if we need something other than "how to run the tests")? That way we would not have to duplicate information between the `http://exercism.io/languages/:track_id` page and the exercise README.

**Comment by ErikSchierboom** [comment]
I like this idea. You effectively separate the general language track setup (which can contain things like installing frameworks etc.) from the test running setup.

**Comment by petertseng** [comment]
I am seeing that a few tracks have a bit of duplicate information between their SETUP and TESTS files:

* [Haskell setup](https://github.com/exercism/xhaskell/blob/master/SETUP.md), [Haskell tests](https://github.com/exercism/xhaskell/blob/master/docs/TESTS.md)
* [Rust setup](https://github.com/exercism/xrust/blob/master/SETUP.md), [Rust tests](https://github.com/exercism/xrust/blob/master/docs/TESTS.md)

(I did not perform a very comprehensive survey, as you can see)

This tells me a few things:

* It could be possible for tracks to deduplicate some of this information if `docs/TESTS.md` would be included in the README.
* At the same time, the migration-process *maybe* needs to involve an opt-in for tracks? If this were suddenly turned on for all tracks, we would actually see some duplicate information in READMEs.

Another thing to consider is that if we value brevity in the README, some tracks have a very brief `SETUP.md` and a more verbose `docs/TESTS.md`

* [Gp setup](https://github.com/exercism/xgp/blob/master/SETUP.md), [Go tests](https://github.com/exercism/xgo/blob/master/docs/TESTS.md)

(again, I was not very comprehensive, sorry)

**Comment by petertseng** [comment]
Seems a little similar to https://github.com/exercism/discussions/issues/63

**Comment by petertseng** [comment]
... and also related to https://github.com/exercism/discussions/issues/42

**Comment by robphoenix** [comment]
I do worry about duplicate information, among many other things in my life, but I believe it's worth keeping `docs/TESTS.md` separate from the exercise README's, so that the docs can provide in depth detailed information, whereas the `TRACK_HINTS` can just be a small reminder of anything pertinent as well as a link to any suggested help/resources, without cluttering up the README making it a TLDR document. If there is any significant concern about duplication I suppose one could always just link to the docs as seen on the exercism.io language track page.

**Comment by kytrinyx** [comment]
It sounds like we decided to keep going as we were. I'm going to close this.
