### ISSUE TITLE
change: strange return value

### ISSUE THREAD

**Issue by dalexj** [exercism/x-common#241]
things I said from https://github.com/exercism/xelixir/pull/174:

> I feel like it would be much nicer for this exercism to return a map of `coin_value` => `amount` rather than an order-dependent list of amounts of the coins

> it seems very strange for me to put the same data in different order to a function and get different results, when the order of the data isn't important (only to specify which coins exist)

any thoughts?

**Comment by kotp** [comment]
I don't believe this is an x-common issue at the moment.

**Comment by dalexj** [comment]
the readme specifically states example input/output https://github.com/exercism/x-common/blob/master/change.md

**Comment by kotp** [comment]
output or return?  Because output is easy.  You said that the return was strange.

**Comment by kotp** [comment]
Going to close this for now.  I don't yet see an issue to address from the x-common point of view.

**Comment by kytrinyx** [comment]
I think the README should remove the array-like thing. The README states input and output ("fewest number of coins") but shouldn't specify any data structures or format.

**Comment by kytrinyx** [comment]
Another question about the README... 15 whats? I don't actually understand the problem description. I'm going to re-open this so that we can clarify.

**Comment by IanWhitney** [comment]
Was this fixed by #249?

**Comment by kotp** [comment]
I think so, just by adding 'coins'?

**Comment by kytrinyx** [comment]
Yeah, I think this is probably fine. We'll probably see more questions about it later if it's not.
