### ISSUE TITLE
Redundant data in anagram.json?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#248]
In exercism/xphp#74 @petemcfarlane noted that we have redundant data in the anagram.json.

Should we remove the redundant cases? Do they serve a particular purpose, e.g. triangulation?

**Comment by IanWhitney** [comment]
22! That's a lot of tests. How many edge cases can there be for an anagram? 

Rust has 11 tests. That seemed fine. Though I imagine most people have a working solution well before they hit their 11th test.

After quickly glancing at the current json file, the following jump out as candidates for removal

- https://github.com/exercism/x-common/blob/master/anagram.json#L60
- https://github.com/exercism/x-common/blob/master/anagram.json#L77
- https://github.com/exercism/x-common/blob/master/anagram.json#L78
- https://github.com/exercism/x-common/blob/master/anagram.json#L102
- https://github.com/exercism/x-common/blob/master/anagram.json#L129
- https://github.com/exercism/x-common/blob/master/anagram.json#L135

A closer inspection would probably turn up more.

**Comment by kotp** [comment]
I might have some students pair on this, for the experience.  Let me find out if I can get some takers... Good subject matter anyway.

**Comment by kytrinyx** [comment]
+1 for having students work on it. It's a great first/early patch.
