### ISSUE TITLE
Where do icons go?

### ISSUE THREAD

**Issue by catb0t** [exercism/x-common#258]
I made an icon for a language on http://exercism.io/languages that doesn't have one yet. I don't see a place for it to go in the language's github repo; where should I send this so someone can review it and add it to the site?

**Comment by catb0t** [comment]
It didn't occur to me that http://exercism.io itself is actually hosted on github. I found where to put the pull.

**Comment by kytrinyx** [comment]
Cool. Eventually we should probably stick this in each of the track repositories... I just hadn't thought that far.
