### ISSUE TITLE
Add instructions on how to extract canonical data to the Contributing Guide

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#261]
We don't have a section on how to survey implementations and create the JSON file with canonical data.

It should probably contain a link to where to find problems that are missing a json file, along with the link to each of the implementations. I thought I created an endpoint for this on x.exercism.io but I can't find it right now.

Also, if we have tips about how to do it / pitfalls / etc, we should include those.

**Comment by kytrinyx** [comment]
Found it: http://x.exercism.io/v3/problems/data-todos

**Comment by petertseng** [comment]
Seems a bit related to #230, unsure if the intent is different

**Comment by kytrinyx** [comment]
No, agreed. This is a duplicate.
