### ISSUE TITLE
The protein-translation and nucleotide-codons exercises are the same

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/x-common#268]
If you look at [the](https://github.com/exercism/x-common/blob/master/nucleotide-codons.md) [docs](https://github.com/exercism/x-common/blob/master/protein-translation.md), you'll find that both these exercises do the exact same thing: they translate codons to there correct names.

One of these exercise should probably be deprecated. Personally, I think the nucleotide-codons is the one that should be deprecated, as its description is to me far less clear than that of the protein-translation exercise.

**Comment by kytrinyx** [comment]
Agreed.

**Comment by petertseng** [comment]
As I ask myself, "how came this to be" and search for answers, it appears that two individuals honestly separately and individually discovered the same exercise, #37 and #93 .

At present, http://x.exercism.io/problems/nucleotide-codons tells me that the only implementing track of nucleotide-codons is Rust. Deprecation will thus not be a whole lot of work. If we strike while the iron is hot.
