### ISSUE TITLE
Alphametics: Description should provide more information.

### ISSUE THREAD

**Issue by Insti** [exercism/x-common#273]
The [description for Alphametics](https://github.com/exercism/x-common/blob/master/alphametics.md) should include the following information:

> Each letter should represent a different digit, and the leading digit of a multi-digit number must not be zero.

Currently this is discoverable by reading the linked wikipedia article, but it should be included in the README text since it is integral to the problem.

**Comment by kotp** [comment]
Looks like the tests do not drive for this, and looks like help is on the way.

**Comment by Insti** [comment]
I also have some objections to the tests, but maybe that should be a in separate issue.
Basically:
a) There are not enough of them.
b) The most elegant Alphametics only use addition.[1]
c) The usage of multiple operators makes it much more difficult to write an optimised solver.[2]

[1] http://www.cadaeic.net/alphas.htm
[2] If the goal is a problem to interpret mathematical formula strings, then just create a problem with that aim, don't pollute an otherwise elegant problem with that requirement as well.

**Comment by kotp** [comment]
Solved by #278
