### ISSUE TITLE
[gigasecond]: Can we clarify gigasecond description?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#302]
From @MariiaKravtsova:

> I found it hard to understand what the problem "Write a program that will calculate the date that someone turned or will celebrate their 1 Gs anniversary." was asking for. I am not sure how to re-word it, but I hope someone can think of a more clear way.

What do you think of rephrasing this to say something like this?

_Write a program that calculates the moment when someone has lived for 1 billion seconds._

**Comment by NobbZ** [comment]
I do not like using the word "billion":

http://www.oxforddictionaries.com/words/how-many-is-a-billion:
> In British English, a billion used to be equivalent to a million million (i.e. 1,000,000,000,000), while in American English it has always equated to a thousand million (i.e. 1,000,000,000). British English has now adopted the American figure, though, so that a billion equals a thousand million in both varieties of English.

Also I do know that there are other languages which use "Billion" for a million million instead of a thousand million, while "giga" should be pretty clear and unambiguous.

Perhaps the best is to simple use this phrase:

_Write a program that calculates the moment when someone has lived for 1'000'000'000 seconds_

**Comment by kytrinyx** [comment]
In Norwegian we don't have _billion_, we have _milliard_. I like your version with the digits much better!

**Comment by wobh** [comment]
We could use some i18n for exercises, not just for what words to use, but for how to represent numbers.

**Comment by kytrinyx** [comment]
I'd rather use standard English notation (numerical) for large numbers than introduce i18n.

**Comment by wobh** [comment]
American English? :-D

Kidding aside, I totally understand.

**Comment by kytrinyx** [comment]
UK and US English have the same format, I think: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

**Comment by wobh** [comment]
`<aside>`North America and the British Isles punctuate numbers are the same, although grouping words differ at 10^6. I'm pretty sure it varies across the Commonwealth. Some places use a comma for a radix point, and a period for grouping. In India--which might or might soon have more English speakers than anywhere else, I'm not sure--they use period for the radix point and comma for grouping, but have a different grouping system.`</aside>`
