### ISSUE TITLE
binary: split error case tests

### ISSUE THREAD

**Issue by Insti** [exercism/x-common#303]
https://github.com/exercism/x-common/pull/296 added a .json data file containing the test cases for this exercise. 

However some of the error case tests had been grouped in an unhelpful way.

>         "description": "numbers other than one and zero raise an error",
>         "binary": ["012", "2"],

This should become 2 cases,

```
         "description": "2 is not a valid binary digit and so should raise an error",
         "binary":  "2",
         "expected" :  null,
```
and

```
         "description": "A number containing an invalid binary digit is invalid and should raise an error",
         "binary":  "01201",
         "expected":  null,
```

Also for
> 
         "description": "invalid binary numbers raise an error",
         "binary": ["012", "10nope", "nope10", "10nope10", "001 nope", "2"],

**Comment by Insti** [comment]
Discussion required: I'm not 100% sure null is the correct expected value here if we want to indicate in a general way that an error should be raised.

**Comment by Insti** [comment]
@tommyschaefer did you want to continue working on this?

**Comment by Insti** [comment]
Thanks again @tommyschaefer you're a :star:

**Comment by tommyschaefer** [comment]
Thank you so much @Insti! It was my pleasure 😄
