### ISSUE TITLE
How to interpret the dot-dsl exercise 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/x-common#331]
I was looking at implementing the [`dot-dsl`](https://github.com/exercism/x-common/blob/master/dot-dsl.md) exercise, but I'm a bit unsure on how to interpret this exercise. Currently, the only language implementing this exercise is Elixir, and their implementation [uses macros](https://github.com/exercism/xelixir/blob/master/exercises/dot-dsl/dot_dsl_test.exs) to define a concrete DSL. 

Should this exercise only be implemented by languages that have specific support for DSL's, or should other languages treat this as a parsing exercise (for which admittedly, the `sgf-parsing` exercise already exists)?

**Comment by NobbZ** [comment]
I do not think that you need to actually need parsers or macros. It should be possible to use different techniques to apply a clean DSL in the implementing language.

Consider some Haskell:

```hs
graph "G" [
  node "foo" [],
  node "bar" [("background", "yellow")],
  edge "foo" "bar" []
]
```

Something similar should be achivable with ruby or python.

Having an EDSL (which would be proper wording in the README I think) does not mean, that you need to strictly reimplement the original language, but to integrate it in a way that it is usable in an idiomatic way in the host language.

**Comment by ErikSchierboom** [comment]
Alright, thanks for the heads up. That seems do-able :)
