### ISSUE TITLE
[secret-handshake]: Clarify readme

### ISSUE THREAD

**Issue by Insti** [exercism/x-common#335]
In reviewing PR #334 I identified a few areas of the [description](https://github.com/exercism/x-common/blob/master/exercises/secret-handshake/description.md) that need clarification:
1. Be explicit about input types and when decimal/binary conversions are appropriate. (Resolved by #489 - answer is never)
2. Make it clearer in the first example that a decimal to binary conversion has happened. (Resolved by #489)
3. Make it clearer in the second example that a reverse has taken place. (Resolved by #489)
4. **What to do about numbers greater than 2^5 ('11111')** ("will not be tested" is fine)
5. The final line: `The program should consider strings specifying an invalid binary as the value 0.` is not particularly useful. (Resolved by #489)

**Comment by petertseng** [comment]
my suggestion of https://github.com/exercism/x-common/pull/159#discussion_r58829790 is that we do not do binary to decimal conversions

**Comment by Insti** [comment]
So this is a bit matching problem and should only have decimal integers as inputs.

**Comment by Insti** [comment]
By NOT updating the description with what to do about numbers greater than 32 we can leave it up to the tracks about whether they want to test them themselves.

Add a comment to the canonical-data.json that says something like:

Numbers greater than 2^5 ('11111') are not tested in this canonical-data, whether to test numbers greater than 32 is left up to the tracks to decide.
