### ISSUE TITLE
Diamond kata's README is unclear about trailing spaces

### ISSUE THREAD

**Issue by rmunn** [exercism/x-common#344]
It looks like I may be the first person (other than its author, of course) to complete the diamond kata, so maybe I'm just misunderstanding the README and other people find it clear. But when I read this test's README, it led me to believe that I should create diamonds that look like this (spaces have been replaced with `·` for clarity):

```plain
····A
···B·B
··C···C
·D·····D
E·······E
·D·····D
··C···C
···B·B
····A
```

However, the unit tests (in the F# version of the exercise, which is the only language in which this exercise seems to have been implemented so far) are checking that leading whitespace is equal to trailing whitespace, which means that the diamond shape the tests are *actually* looking for would be:

```plain
····A····
···B·B···
··C···C··
·D·····D·
E·······E
·D·····D·
··C···C··
···B·B···
····A····
```

Finally, the diamond shape example that the README *actually contains* looks like this once I replace its space characters with `·`:

```plain
····A·······
···B·B···
··C···C·
·D·····D
E·······E
·D·····D···
··C···C
···B·B
····A
```

That's clearly in need of editing. :-)

I suggest that the README should be more explicit about the fact that trailing spaces are expected in this exercise, and should also use the `·` character to make the trailing spaces visible in the examples. (And, of course, the examples should match what the unit tests are expecting, but that almost goes without saying. :-) )

**Comment by ErikSchierboom** [comment]
@rmunn You are completely correct, the readme is not clear about the trailing spaces (which are an essential part of the exercise). Would you be willing to do a PR for the [Diamon readme file](https://github.com/exercism/x-common/blob/master/diamond.md)?

**Comment by Insti** [comment]
We also have a version in [xruby](https://github.com/exercism/xruby/tree/master/exercises/diamond) which expects the line lengths to be equal and whitespace padded. (It might not be available on the live site yet.)
