### ISSUE TITLE
pangram: tests not pending

### ISSUE THREAD

**Issue by Trevoke** [exercism/x-common#354]
Just pulled the pangram exercise for Scala and no tests are pending.

**Comment by petertseng** [comment]
Since you mentioned it's for Scala, it seems that it would be better to put the issue at https://github.com/exercism/xscala

unless it is known to us that multiple tracks have this same problem (even then, though, individual issues in the respective tracks would probably be best)

**Comment by Cohen-Carlisle** [comment]
Closing this as I've created the issue for scala https://github.com/exercism/xscala/issues/131
