### ISSUE TITLE
jsonlint should look for JSON files at their post-re-organisation locations

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#371]
#351 moved files from the root of this repo to per-problem subdirectories under `exercises/`.

However, jsonlint still searches for files in the root of this repo only because its glob at https://github.com/exercism/x-common/blob/master/bin/jsonlint#L4 is `*.json`.

This means that we are not getting JSON validation on any JSON files currently.

**Comment by kytrinyx** [comment]
Ah, good catch. I'll fix that now.
