### ISSUE TITLE
Finish deprecating `counter`

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#383]
The `counter` exercise is deprecated.

We added a deprecation notice to the [README](https://github.com/exercism/x-common/blob/master/exercises/counter/description.md), but they're still showing up in the various tracks' TODO lists, since they're not deprecated in the various `config.json` files. E.g. http://exercism.io/languages/ruby/contribute

We have a couple of options here:

1. Submit an issue to each track to ask them to add `counter` to the `foregone` array
2. Implement something globally that lets us mark an exercise as deprecated

I like 2 better.

The simplest thing I can think of is to stick an empty file named `.deprecated` (or something like that) in the exercise subdirectory (https://github.com/exercism/x-common/tree/master/exercises/counter)

Ref: https://github.com/exercism/exercism.io/issues/3103

For more context about why it was deprecated, see https://github.com/exercism/x-common/issues/80

**Comment by NobbZ** [comment]
My proposal at exercism/discussions#40 would mean to deprecated globally anyway. So I vote for 2 as well.

**Comment by kytrinyx** [comment]
Here's the x-api issue: https://github.com/exercism/x-api/issues/139

**Comment by mixolidia** [comment]
I'm working on this tomorrow & then on. I will have questions. :)

**Comment by kytrinyx** [comment]
@mixolidia I just merged https://github.com/exercism/x-api/pull/140 from @ramyaravindranath I didn't see your note about taking this one on until today, I hope that (a) this wasn't frustrating and (b) we didn't just throw away a bunch of your work! :heart:

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/x-api/pull/140

**Comment by petertseng** [comment]
That allows counter to be deprecated, but has action been taken to deprecate it?

What I mean is: I don't see the .deprecated file in this repo (should I?)

**Comment by kytrinyx** [comment]
Nope, you're absolutely right.

**Comment by ErikSchierboom** [comment]
This has been fixed in [this PR](https://github.com/exercism/x-common/pull/407).
