### ISSUE TITLE
Finish deprecated `point-mutations`

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#384]
See https://github.com/exercism/x-common/issues/383 for the equivalent issue about `counter`.

The Point Mutations problem is deprecated, per its [README](https://github.com/exercism/x-common/blob/master/exercises/point-mutations/description.md). It's been replaced with `hamming`.

The old and messy reason for this is... well, old and messy. In the early days we didn't support multi-word exercise names very well. We have since fixed all the problems related to that, but the problem is still deprecated, and we should tie up any loose ends.

There aren't any tracks that implement the exercise, but it's showing up in the "todo" lists for any track that hasn't explicitly put it in "deprecated" or "foregone" in the `config.json` for the track.

We have two choices:

1. Submit an issue to each track (using https://github.com/exercism/blazon) which asks them to make sure it's in foregone or deprecated.
2. Support deprecating problems globally.

I like 2 better.

Once we figure out in https://github.com/exercism/x-common/issues/383 what we want to do with counter, let's do the same thing with this one.

See https://github.com/exercism/exercism.io/issues/3103 for context.

**Comment by NobbZ** [comment]
My proposal at exercism/discussions#40 would mean to deprecated globally anyway. So I vote for 2 as well.

**Comment by kytrinyx** [comment]
OK, I'll write up an issue in x-api that describes what we need to support.

**Comment by kytrinyx** [comment]
Here it is: https://github.com/exercism/x-api/issues/139

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/x-api/pull/140

**Comment by petertseng** [comment]
That allows point-mutations to be deprecated, but has action been taken to deprecate it?

What I mean is: I don't see the .deprecated file in this repo (should I?)

**Comment by kytrinyx** [comment]
Oh, no you're right. We need to add the deprecated file.

**Comment by ErikSchierboom** [comment]
This has been fixed by [this PR](https://github.com/exercism/x-common/pull/406).
