### ISSUE TITLE
Grains exercise may need more tests

### ISSUE THREAD

**Issue by Trevoke** [exercism/x-common#385]
There's not much reason to write logic for the `total` method since it's never going to change: it's always the sum of all 64 squares. Why not add an argument for how many squares to count up to, and some tests to reflect that?

**Comment by Insti** [comment]
Which language is this?

It is useful to test that `total` returns the correct value, and in Ruby we have tests for the total and for the number of grains on some of the squares.

Closing this now, but if you want to you are welcome to create a pull request for the `exercises/grains/canonical-data.json` file that contains the tests you think are relevant.
