### ISSUE TITLE
Alphametics: simplify or split into two exercises

### ISSUE THREAD

**Issue by ijanos** [exercism/x-common#395]
I think the current Alphamatics exercise contains two separate problems.

* The original alphametics problem where you have to find letter-number substitutions. 
* Correctly parse a strings containing arbitrary mathematical formulas, with different operators and correct precedence. 

Solving the second part correctly requires different knowledge and most likely take longer to solve for most people. I guess in a dynamic language you can do this part through `eval` trickery, but that is not elegant and not available for less-dynamic languages. 

I can see people creating a partial parser or hardcode patterns that will satisfy all the test-cases and stop there, that would send the message that the goal of tests is to pass them and don't care about the general problem.

I see the following solutions: 
- Simplify the exercise to only use addition, this makes parsing puzzles much more easier. Then possibly split the formula parser into its own exercise without the alphametics part. 
- Create a separate "formula parser" exercise and make it clear that it should be solved before and extended for the alphametics puzzle.

This problem was briefly mentioned by @Insti in another not related issue: https://github.com/exercism/x-common/issues/273#issuecomment-226616740

**Comment by Insti** [comment]
I'd like to see Alphametics transformed into a Pure Alphametics version that only uses addition.

I don't care so much about the formula parser portion, but that does make a nice separate problem.

**Comment by Insti** [comment]
Hooray, thanks @ijanos :heart:
