### ISSUE TITLE
README of atbash-ciper mentions group size, but there are no tests for it

### ISSUE THREAD

**Issue by dvberkel** [exercism/x-common#398]
The [atbash-ciper exercise](https://github.com/exercism/x-common/blob/master/exercises/atbash-cipher/description.md) describe the _group size_, i.e. the size of the group that characters are grouped by.

When I ported this exercise I interpreted it as to provide a means to alter the group size, but the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/atbash-cipher/canonical-data.json) does not provide tests for this scenario.

It this something to address? Either by
1. Changing the description in the README.
2. Provide tests for group size

Or are we happy, just the way we are?

**Comment by jtigger** [comment]
Personally, I'm happy the way we are.  The group size of 5 is given which matches the canonical data.

Perhaps strengthen the suggestion to use 5?

**Comment by jtigger** [comment]
@dvberkel and @stevejb71 included a test for different group sizes in exercism/xocaml#72. With that example in hand, @exercism/track-maintainers should we update the exercise across the tracks?

**Comment by Insti** [comment]
> should we [update the exercise to test for group sizes other than 5]

No. 

The main point of this exercise is the encoding. This is what should be tested for.
If grouping is an interesting problem it should have it's own `group-size` exercise.

**Comment by dvberkel** [comment]
I am happy not porting this to all language tracks. We could close this issue, if no other opinions emerge.

**Comment by kytrinyx** [comment]
> Or are we happy, just the way we are?

I think we're happy just the way we are :heart:
