### ISSUE TITLE
Sieve of Eratosthenes: Inclusive versus Exclusive

### ISSUE THREAD

**Issue by Dog** [exercism/x-common#41]
It was brought up in xpython that the README for this problem is vague. I feel the README for this problem should be updated to explicitly state if it is inclusive or exclusive of the limit. This would be `[2, limit)` vs `[2, limit]`

Here is a quote from the README:

`Create your range, starting at two and ending at the given limit.`

"Ending" could mean finish after considering the limit, or break once we get to the limit.

I don't think it matters much if we chose inclusive or exclusive. I think we should just pick one and stick with it to be consistent. At the moment I lean towards inclusive, because I have the feeling this would be more natural for readers when considering the problem.

Does anyone else have an opinion on this?

**Comment by kytrinyx** [comment]
I don't feel strongly either way, and agree that consistency (and explicitly stating the problem) would be good.
