### ISSUE TITLE
[isogram] Test descriptions

### ISSUE THREAD

**Issue by Insti** [exercism/x-common#410]
When generating test cases it is useful to have a `description` that can be used to generate test names. 

The [isogram canonical-data](https://github.com/exercism/x-common/blob/master/exercises/isogram/canonical-data.json) is missing this field.

When working out a good description for a case it can be useful to browse the [issues and pull requests relating to isogram](https://github.com/exercism/x-common/search?q=isogram&type=Issues&utf8=%E2%9C%93) for discussion about why certain cases were added.

See also [the word-count canonical data](https://github.com/exercism/x-common/blob/master/exercises/word-count/canonical-data.json) for a good example of `description` in use.

**Comment by behrtam** [comment]
I was working on the isogram data #433 because of the unicode removal and felt the descriptions where missing, so I kind of accidentally solved this issue.

**Comment by Insti** [comment]
Resolved by #433
