### ISSUE TITLE
sublist: Possible missing edge case

### ISSUE THREAD

**Issue by behrtam** [exercism/x-common#432]
Found a clever implementation ([link](http://exercism.io/submissions/576e9759b6c34816ae204812388f58c4)) in Python for the sublist exercise that shouldn't pass all tests. It basically joins all the digits (`[1, 2, 3] -> "123"`) and uses the `in` operator that checks if one string is a substring of the other.

If we would have two list `[1, 0, 1]` and `[10, 1]` that particular solution would create two strings `"101"` and `"101"` and determine incorrectly that those lists are equal. Is this way to solve this too unlikely or should we add this as a test case?

**Comment by Insti** [comment]
I think that is a good test case to add. :+1: 

Part of a good test suite is detecting things that pass that should not.
