### ISSUE TITLE
[perfect-numbers] Description is not clear

### ISSUE THREAD

**Issue by snahor** [exercism/x-common#447]
The description isn't very clear, I mean it's not clear what to implement. I've been looking at the implementations and there's no consensus. Some of them implement the classification and the others just check whether or not the number is perfect.

**Comment by Insti** [comment]
[Perfect numbers description](https://github.com/exercism/x-common/blob/master/exercises/perfect-numbers/description.md)

**Comment by Insti** [comment]
I would suggest doing something like what we have recently done for triangles. [Triangles test data](https://github.com/exercism/x-common/blob/master/exercises/triangle/canonical-data.json)

Where there are 3 different functions that return a boolean value depending on if the number is  Perfect, Deficient, or Abundant

**Comment by guntbert** [comment]
Looking at _Triangles_ I see that `metadata.md` contains a clear statement what to do 

> Write a program that can tell you if a triangle is equilateral, isosceles, or scalene.

This statement is missing here.

**Comment by guntbert** [comment]
@Insti this might be a good "first patch"

**Comment by petertseng** [comment]
Naturally, one might ask: Is #481 sufficient to close this issue?

It certainly has helped greatly in this regard.

I think a little help in the README would be good - so perhaps https://github.com/exercism/x-common/blob/master/exercises/perfect-numbers/description.md could also say that we need to be able to determine whether a given number is perfect, abundant, deficient. 

The sentence on the Aliquot sum also seems a bit out of place.

**Comment by petertseng** [comment]
> perhaps https://github.com/exercism/x-common/blob/master/exercises/perfect-numbers/description.md could also say that we need to be able to determine whether a given number is perfect, abundant, deficient.

#518 takes care of that.
