### ISSUE TITLE
Fail the travis build if an exercise is missing critical files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#457]
Everything on Exercism assumes that an exercise has at the very least a `description.md` file and a `metadata.yml` file.

If one of these files is missing in an exercise, then the build should break.

See discussion here for context: https://github.com/exercism/trackler/pull/6/commits/036a2a7f579aa29e4815cf32dd285105a810de0b#r90053608

**Comment by rpottsoh** [comment]
Should I be concerned about these files at this point?  Is this something I should be looking in to?


Sent from my android device.

**Comment by kytrinyx** [comment]
@rpottsoh No, you only need to worry about this if you make up a completely new exercise.

**Comment by rpottsoh** [comment]
@kytrinyx PR #14 (Harry Potter) is not a conversion from another Exercism track.  Tell me what I need to know, or at least point me in the right direction. J

**Comment by tejasbubane** [comment]
I am working on writing a shell script similar to https://github.com/exercism/x-common/blob/master/bin/jsonlint.

**Comment by kytrinyx** [comment]
@rpottsoh Ah, excellent. In that case this section of the Contributing Guide should have what you need: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise

**Comment by petertseng** [comment]
Please correct me if I'm wrong but I think the merging of #458 resolves this.
