### ISSUE TITLE
Definition of "sublist" in sublist exercise

### ISSUE THREAD

**Issue by tstirrat15** [exercism/x-common#46]
I recently submitted a pull request to xpython regarding what I thought "sublist" should mean in the context of this problem, and @sjakobi redirected me here.

In my reading of the problem, a list is essentially a set that allows repetition - order doesn't matter, inherently. The way that the tests are written treats the lists more like words, where order does matter.

Given that there's this ambiguity in the concept of lists, can we change the problem specification to clarify this? I don't have an opinion on which way to change things, but it should go one of two ways:
* Clarify that order doesn't matter in a list, and change `test_spread_sublist` and its equivalents so that `multiples_of_15` is a sublist of `multiples_of_3`
* Clarify that order does matter in a list, and keep the tests as they are.

On a related note, I've only had any real experience with Python. Are lists handled in a different way in other languages such that it's less of an issue?

**Comment by kytrinyx** [comment]
My immediate thought is that a list is ordered, whereas a set would be unordered.

@pminten Do you have an opinion about this?

**Comment by pminten** [comment]
In all languages I know list is ordered. An unordered collection that allows duplicates is often called a multiset.

Katrina Owen <notifications@github.com> schreef op 30 januari 2015 05:50:11 CET:
>My immediate thought is that a list is ordered, whereas a set would be
>unordered.
>
>@pminten Do you have an opinion about this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/x-common/issues/46#issuecomment-72153920

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by sjakobi** [comment]
Sorry for the confusion. This has nothing to do with sets IMO. Here's my orginial response to @tstirrat15's [PR](https://github.com/exercism/xpython/pull/166):

> The same test case was recently discussed in https://github.com/exercism/xpython/issues/154.

> The problem is that we have no proper definition of "sublist". The [readme](https://github.com/exercism/x-common/blob/master/sublist.md) simply isn't sufficiently precise about what it means that a list is contained within another.

> If "sublist" means ["subsequence"](http://en.wikipedia.org/wiki/Subsequence), the test case should indeed be changed as proposed by you.
If "sublist" means ["substring"](http://en.wikipedia.org/wiki/Substring) instead, the testsuite is correct as it stands.

> I'd really appreciate it if you would open an issue in the x-common repo and try to settle this question for good!

If we take a list A = [1, 2, 3] and a list B = [1, 3] then B is a subsequence of A but not a substring of A. But the [readme on the problem](https://github.com/exercism/x-common/blob/master/sublist.md) is so vague that I'm not sure whether B is supposed to be a sublist of A or not.

**Comment by kytrinyx** [comment]
Thanks for clarifying @pminten @sjakobi -- I would suggest that this README be altered to explicitly state that the sublist means consecutive entries.

**Comment by tstirrat15** [comment]
Cool! Thank you guys for clarifying this. And this process was pretty cool - this is the first time that I've contributed to any sort of open-source project. I'd like to contribute to this project - is there some aspect of this project that needs more help than another?

**Comment by kytrinyx** [comment]
@tstirrat15 Thank you for offering! What kind of development 

One thing that I'm trying to do is to make the overall documentation welcoming and useful to make it easier for people to contribute.

https://github.com/exercism/exercism.io/issues/2163

Another thing is to try to make it easier to understand what exercism is all about when you join, and as you're getting started with it. I saw a video of a quick presentation that someone did at a meetup a couple days ago, and it's clear that the whole onboarding process is really confusing: https://www.youtube.com/watch?v=WTQyZXHvAO0#t=385

In general the user-interface on the website is haphazard and klunky, and any improvements there would be welcome.

**Comment by tstirrat15** [comment]
I can totally start with documentation.

I'm just starting to get my feet wet in programming - I'm a Math student in my senior year, but I think I might enjoy programming enough to want to make a career out of it, so I've been diving in, so to speak.

I don't have a whole lot of experience in Go or Ruby, so I don't think I'm ready to start screwing around with the backend, but I've been having a lot of fun with the Python exercises, and I could help with clarifying the READMEs there and in xcommon.

It sounds like looking at issues would be a good place to start, too - just trying to get a handle on the various problems that people are having and whether they're easily fixable.

**Comment by kytrinyx** [comment]
> I've been having a lot of fun with the Python exercises, and I could help with clarifying the READMEs there and in xcommon.

That would be immensely helpful!

> It sounds like looking at issues would be a good place to start, too - just trying to get a handle on the various problems that people are having and whether they're easily fixable.

This is also something that I would appreciate very much. I think it's likely that there are categories of problems/requests that could be curated and organised much more effectively than I'm doing, and an extra pair of eyes (not to mention a fresh perspective) could probably be very beneficial here.
