### ISSUE TITLE
variable-length-quantity: why 0x0fffffff max?

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#485]
readme:

> The largest integer allowed is 0FFFFFFF, which translates to 4 bytes variable length.

This echoes http://web.archive.org/web/20051129113105/http://www.borg.com/~jglatt/tech/midifile/vari.htm and http://www.music.mcgill.ca/~ich/classes/mumt306/midiformat.pdf#page=2

Does it have to be this way? the 0x0fffffff max was meant for midi files, but https://en.wikipedia.org/wiki/Variable-length_quantity says 

> A variable-length quantity (VLQ) is a universal code that uses an **arbitrary** number of binary octets (eight-bit bytes) to represent an **arbitrarily** large integer.

The emphasis on "arbitrary" is mine. Given that in general these values can be arbitrary, does it makes sense to include the sentence on limitations in the README?

And the Rust track has a test for 0xffffffff. But that violates the README, so https://github.com/exercism/xrust/issues/224

I say it doesn't make sense to include the limitation in the README.

**Comment by petertseng** [comment]
Implementing tracks http://x.exercism.io/problems/variable-length-quantity

["csharp","fsharp","go","lua","php","rust"]

**Comment by petertseng** [comment]
* C# also tests 0xffffffff
* F# also tests 0xffffffff
* Go doesn't.
* Lua doesn't.
* PHP doesn't.
* Rust does.

**Comment by Insti** [comment]
meh. 
Create a canonical-data set for it and you can make the maximum whatever you like, and adjust the description appropriately.
