### ISSUE TITLE
topics: add equality

### ISSUE THREAD

**Issue by bordeltabernacle** [exercism/x-common#494]
I noticed the topic `Structural equality` in the F# track [here](https://github.com/exercism/xfsharp/blob/master/config.json#L135).

Is it worth adding an equality topic to the `TOPICS.txt` list? This is derived mostly from the [Clock exercise](https://github.com/exercism/x-common/blob/master/exercises/clock/description.md).

Not necessarily `Structural equality`, maybe `Relational equality`, `Equality comparison`, `Equality testing` or just `Equality` ??

Honestly, I don't have the experience to make a judgement on this, especially with regards to different interpretations of equality by different languages.

**Comment by rpottsoh** [comment]
@bordeltabernacle how about something along the lines of `Operations`?  ie. =, +, - , / , *, etc.

**Comment by bordeltabernacle** [comment]
I'm not sure, I was considering less some kind of mathematical operation and more the assessment of one *thing* being the same as another. For instance in the clock exercise we're told that `Two clocks that represent the same time should be equal to each other.` The term `structural equality` seems to fit better here than the concept of an operation. I realise this can mean different things in different languages, and I guess it's that idea of how is one type or object equal or different to another?

**Comment by Insti** [comment]
Just `Equality` seems reasonable for a topic.

**Comment by rpottsoh** [comment]
OK.  How about both `Equality` and `Operations`?  Generally speaking `Operations` seems to be missing to me.

**Comment by Insti** [comment]
Are there any problems that *don't* use operations?

**Comment by rpottsoh** [comment]
@Insti :smile:  I doubt it.  I only mention it here as a matter of course.  How consice should topics.txt be, or what is the purpose of topics.txt?

**Comment by Insti** [comment]
In order to categorise exercises for future searching, tracks can add the topic(s) of exercises  to their `config.json` file. In order to maintain some cross-track consistency, there is currently no enforcement of this, the `topics.txt` list acts as an overall master list that tracks can refer to.

There's a big discussion about it here: https://github.com/exercism/discussions/issues/60

**Comment by rpottsoh** [comment]
@insti thanks for pointing me to that issue.  With the entirety of that issue fresh in my mind `Equality`, as you suggest, would be a good addition to consider.

**Comment by bordeltabernacle** [comment]
Thanks @insti I'll open a PR to add `Equality`. Also interesting to note that `topics.txt` is not an enforced list for languages to adhere to. I did wonder that seeing the F# `config.json`
