### ISSUE TITLE
bank-account: short description is not very descriptive

### ISSUE THREAD

**Issue by stkent** [exercism/x-common#498]
Compare the short description of `bank-account`:

<img width="508" alt="screen shot 2017-01-14 at 11 15 12 pm" src="https://cloud.githubusercontent.com/assets/6463980/21960199/b1c13c1a-daaf-11e6-9aa9-2a7a7a388fe8.png">

to that of, e.g., `diamond`:

<img width="523" alt="screen shot 2017-01-14 at 11 15 18 pm" src="https://cloud.githubusercontent.com/assets/6463980/21960201/b5186118-daaf-11e6-8cc7-fdc4791efa0a.png">

The short description for `bank-account` is a statement of fact; not a description of what the exercise entails. We should improve it!

**Comment by robkeim** [comment]
Just sent this PR with an updated description:
https://github.com/exercism/x-common/pull/525

**Comment by robkeim** [comment]
@stkent this should now be fixed, let me know if you think it needs more work!
