### ISSUE TITLE
scrabble-score: add tests for optional extensions? (:double/:triple letter values)

### ISSUE THREAD

**Issue by juleskers** [exercism/x-common#511]
In the scrabble-score exercise, there is the optional section to implement the double-letter-value mechanism. However, there are no tests to guide one when doing this.

I stumbled over this while implementing scrabble-score for the rust-track.
[My pull-request](https://github.com/exercism/xrust/pull/249) against xrust was redirected here for broader discussion.

Should we add tests for this optional section? Or are those intentionally not included to encourage the exerciser to try his/her hand at test-writing?

**Comment by Insti** [comment]
> Should we add tests for this optional section? 

No

I also wrote about this here: https://github.com/exercism/x-common/issues/512#issuecomment-275047297

> The main problem that should be well described and covered by the canonical-data tests is just the word scoring.

> The discussion about how to implement the extensions is part of the extended work and should not be specified in the problem description.

**Comment by juleskers** [comment]
Thanks for the feedback! I'll stop work in that direction then.
