### ISSUE TITLE
meetup: Improve description

### ISSUE THREAD

**Issue by hobbitjoe** [exercism/x-common#515]
The description for this problem could be worded a bit better so its more clear as to what the problem actually is.  It only becomes clear after reading the tests that given a day of the week, month, year, and modifier (?? not sure how to describe this) return the corresponding date.

Examples:
First Monday of January 2017             ->  2017/1/2
Second Wednesday of January 2017  ->  2017/1/11
Tuesteenth of January 2017                ->  2017/1/17
Fourth Thursday of January 2017       -> 2017/1/26

**Comment by Insti** [comment]
https://github.com/exercism/x-common/blob/master/exercises/meetup/description.md

**Comment by sbeidels** [comment]
I would like to work on this clarification.  It seems like a good place to start contributing! :)
