### ISSUE TITLE
rna-transcription: complement_test instead of rna-transcriptionTest?

### ISSUE THREAD

**Issue by masters3d** [exercism/x-common#52]
I noticed that rna-transcription is referenced as the Complement in Ruby and C#. Should these be referenced instead by rna-transcription_test as in python for example. 
https://github.com/masters3d/x-common/blob/master/rna-transcription.yml
https://github.com/masters3d/xruby/blob/master/rna-transcription/complement_test.rb
https://github.com/masters3d/xcsharp/blob/master/rna-transcription/ComplementTest.cs

**Comment by kytrinyx** [comment]
It doesn't really matter what we call the test file. At the moment I don't think it's important enough to change, but if you have a good argument, I'm quick to change my mind.

**Comment by masters3d** [comment]
Sounds good. I was just curious on the naming. Something I saw on Hacker News that reminded me of this.  https://www.quantamagazine.org/20150206-crispr-dna-editor-bacteria/
