### ISSUE TITLE
[run-length-encoding] test case conflicts with description

### ISSUE THREAD

**Issue by daveyarwood** [exercism/x-common#537]
The [description](https://github.com/exercism/x-common/blob/master/exercises/run-length-encoding/description.md) of the run-length-encoding exercise says:

> For simplicity, you can assume that the unencoded string will only contain the letters A through Z.

However, there is [one test case](https://github.com/exercism/x-common/blob/master/exercises/run-length-encoding/canonical-data.json#L47-L49) that contains spaces and lowercase letters.

I believe the test case should be changed to something like `OEJJJJJXAAPPPL`, the intent being that all of the test cases deal with strings containing only uppercase letters. I could make a PR to fix this test case, if you'd like?

**Comment by robkeim** [comment]
Thanks @daveyarwood for pointing this out!

I added that description trying to fix #238, but as you pointed out my description was not complete. I think the correct thing to do would be to update the description to say something like:
"only letters A through Z (upper and lower case) as well as white space".

**Comment by daveyarwood** [comment]
I wonder if that would create more work for the individual language repos? The example solutions would all need to be updated to handle spaces in the input.

**Comment by robkeim** [comment]
Tracks that have already implemented this exercise should have been taking the existing whitespace into account (assuming that they're following the canonical data). Therefore, I think it makes more sense to not modify the canonical data and to update the description.

**Comment by daveyarwood** [comment]
Ah, that's a good point. 👍

**Comment by robkeim** [comment]
If you'd like to send a PR with an updated description go right ahead, otherwise let me know and I'll give it another shot.

**Comment by daveyarwood** [comment]
I'm happy to take a stab at it.

Question, though: what about the lowercase z's? Are we considering valid input to be only uppercase letters and whitespace?

**Comment by robkeim** [comment]
My understanding, given the current canonical data, is that we're accepting all ASCII characters except for the numbers, although the tests only test A through Z both upper and lowercase.

Here's another attempt (tell me what you think):
> For simplicity, you can assume that the unencoded string only contains whitespace and the letters A through Z both upper and lowercase.

**Comment by daveyarwood** [comment]
That sounds good to me 👍 

I'll make a PR soon to update the description when I have a little bit of free time.
