### ISSUE TITLE
diamond: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#556]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Diamond exercise can be found in the [./exercises/diamond/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/diamond for the up-to-date list of
language tracks that have an implementation of the Diamond exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/diamond

**Comment by stkent** [comment]
I'll happily pick this issue up: I recently built the exercise for the Java track and so surveyed the existing implementations.

**Comment by petertseng** [comment]
And while we're on the discussion, I'll go ahead and say it can be interesting to encourage tracks to use some property-based testing rather than example-based testing, as indicated in the discussion of the PR that introduced the exercise: https://github.com/exercism/x-common/pull/191#issuecomment-254378776

**Comment by stkent** [comment]
Mmm, interesting. I am not sure how best to capture "write tests according to this philosophy if possible, but if not according to this other philosophy" in the existing canonical data structure. Any suggestions?

**Comment by petertseng** [comment]
Me neither! Adding another facet to this problem, the property-based philosophy is at best unnatural to encode into JSON. I imagine that at best it would only be able to include something like the bulleted list in the README and then it is up to the individual tracks to implement the actual checks. In contrast, example-based tests are very easy to encode.

Indeed, in the `domino` problem, there is also the choice between example-based testing (true or false) versus property-based testing (https://github.com/exercism/x-common/blob/master/exercises/dominoes/canonical-data.json#L27). The best I came up with at the time was to leave a very lengthy comment in the file.

Even today I do not have a better suggestion. It may be that the example-based tests can go in the JSON file, with a comment saying "try out property-based testing".

**Comment by ErikSchierboom** [comment]
Interesting problem. What I did when I created this exercise, is to setup the tests such that they could be solved using regular example based tests (using a couple of standard input letters), but that they are actually perfectly suited to property-based testing.

For example, I have a test `Diamond has square shape`, which is clearly a property test. For the F# track, I then chose not to use an actual full-fledged property-based testing framework, but to simply use parameterized tests with the parameterized values being the characters from 'a' to 'z'.

Maybe the best we can do is say something about how track implementers could try to write property-based tests when implementing it?

**Comment by stkent** [comment]
Existing implementations:

[xcsharp](https://github.com/exercism/xcsharp/blob/master/exercises/diamond/DiamondTest.cs)
[xecmascript](https://github.com/exercism/xecmascript/blob/master/exercises/diamond/diamond.spec.js)
[xelixir](https://github.com/exercism/xelixir/blob/master/exercises/diamond/diamond_test.exs)
[xfsharp](https://github.com/exercism/xfsharp/blob/master/exercises/diamond/DiamondTest.fs)
[xgo](https://github.com/exercism/xgo/blob/master/exercises/diamond/diamond_test.go)
[xjava](https://github.com/exercism/xjava/blob/master/exercises/diamond/src/test/java/DiamondPrinterTest.java)
[xjavascript](https://github.com/exercism/xjavascript/blob/master/exercises/diamond/diamond.spec.js)
[xlua](https://github.com/exercism/xlua/blob/master/exercises/diamond/diamond_spec.lua)
[xpython](https://github.com/exercism/xpython/blob/master/exercises/diamond/diamond_test.py)
[xruby](https://github.com/exercism/xruby/blob/master/exercises/diamond/diamond_test.rb)

**Comment by stkent** [comment]
Observations:

- 3/10 implementations use property-based testing; 7/10 use value-based
- 4/10 implementations test both boundaries (A and Z)
- 5/10 implementations test exactly the cases from the problem description, A, C, and E, and therefore never test an "even" letter (A, C, and E have positions 1, 3, and 5 within the alphabet)

**Comment by stkent** [comment]
I have to admit, this problem was my first exposure to property-based testing! It's an interesting approach. I'm not sure that the existing problem description, which describes the desired output in terms of its properties, is ideal - it doesn't really suit languages that currently use value-based testing. I'd be interested in making the description more "typical", and leaving it up to each track to decide whether this is an appropriate place to introduce the concept of and tooling around property-based testing. In terms of the canonical test data; I'm on board with @petertseng's suggestion to describe typical value-based tests, and use the canonical data's description block as a way to nudge implementors towards a property- based approach if they are feeling adventurous.

**Comment by stkent** [comment]
If using value-based testing, the following cases seem sufficient:

- A (unique case: only one 'A' row)
- B (unique case: no spaces between the central row of characters)
- C (smallest typical case for an "odd" character)
- D (smallest typical case for an "even" character)
- Z (boundary case)

**Comment by ErikSchierboom** [comment]
@stkent I think having those five test cases should indeed be sufficient. As long as we state somewhere in the comments that this exercise's test suite could also use property-based testing, I think it very much makes sense to use the value-based tests for the canonical data.

**Comment by stkent** [comment]
@ErikSchierboom awesome; how does the comment in https://github.com/exercism/x-common/pull/612 look to you?

**Comment by ErikSchierboom** [comment]
@stkent Nothing to add, looks perfect to me! Great work. :thumbsup:
