### ISSUE TITLE
hexadecimal: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#563]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Hexadecimal exercise can be found in the [./exercises/hexadecimal/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/hexadecimal for the up-to-date list of
language tracks that have an implementation of the Hexadecimal exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/hexadecimal

**Comment by NobbZ** [comment]
Hasn't this got deprecated in favor of `all-your-base` alongside of `binary`, `trinary`, and `octal`?

**Comment by kytrinyx** [comment]
It should be, but it apparently doesn't have a `.deprecated` file. I'll open an issue.

**Comment by kytrinyx** [comment]
There's already an open issue: https://github.com/exercism/x-common/issues/279
