### ISSUE TITLE
Rename "linked list" to "singly-linked list" on all tracks

### ISSUE THREAD

**Issue by masters3d** [exercism/x-common#57]
Do you think there is a benefit in renaming all current tracks to "singly-linked list"?

https://github.com/exercism/x-common/pull/56

I can do the pull request to these tracks if you think that is something we should do. 

CoffeeScript
C#
Haskell
JavaScript
Perl 5
Ruby
Scala

**Comment by kytrinyx** [comment]
If we rename it, then we'll have to make sure to run a script so that people don't get the new one as though they've never solved it.

@etrepum -- what do you think. Is it worth renaming the exercise? Or does it not necessarily matter either way?

**Comment by etrepum** [comment]
"singly linked list" is generally implied by the unqualified term "linked list", so this change would make it more explicit but not really more precise. Doesn't matter much either way, I doubt it's worth the migration effort.

**Comment by masters3d** [comment]
Sounds good. Thanks for looking into this.
