### ISSUE TITLE
octal: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#571]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Octal exercise can be found in the [./exercises/octal/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/octal for the up-to-date list of
language tracks that have an implementation of the Octal exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/octal

**Comment by NobbZ** [comment]
Hasn't this got deprecated in favor of `all-your-base` alongside of `binary`, `trinary`, and `hexadecimal?`

**Comment by stkent** [comment]
Yes, this exercise is deprecated as you indicated!

**Comment by kytrinyx** [comment]
It should be deprecated, but it isn't yet. The open issue is https://github.com/exercism/x-common/issues/279
