### ISSUE TITLE
perfect-numbers: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#575]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Perfect Numbers exercise can be found in the [./exercises/perfect-numbers/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/perfect-numbers for the up-to-date list of
language tracks that have an implementation of the Perfect Numbers exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/perfect-numbers

**Comment by stkent** [comment]
I just built this for the Java track. The tests I ended up with consist of:

- For each classification (perfect, abundant, deficient):
    - a small test case to get started
    - a medium test case that can still be computed by hand
    - a very large test case that would be difficult to computed by hand

Actual test cases:

6 is perfect
28 is perfect
33550336 is perfect
12 is abundant
24 is abundant
33550335 is abundant
8 is deficient
31 is deficient
33550337 is deficient

These cases also cover all the examples given in the problem description (6, 28, 12, 24, 8). Thoughts on these tests before I try translating them into the latest and greatest canonical data format?

**Comment by stkent** [comment]
Existing implementations:

[xcsharp](https://github.com/exercism/xcsharp/blob/master/exercises/perfect-numbers/PerfectNumbersTest.cs)
[xclojure](https://github.com/exercism/xclojure/blob/master/exercises/perfect-numbers/test/perfect_numbers_test.clj)
[xdelphi](https://github.com/exercism/xdelphi/blob/master/exercises/perfect-numbers/uPerfectNumbersTest.pas)
[xelisp](https://github.com/exercism/xelisp/blob/master/exercises/perfect-numbers/perfect-numbers-test.el)
[xfsharp](https://github.com/exercism/xfsharp/blob/master/exercises/perfect-numbers/PerfectNumbersTest.fs)
[xgo](https://github.com/exercism/xgo/blob/master/exercises/perfect-numbers/perfect_numbers_test.go)
[xjava](https://github.com/exercism/xjava/blob/master/exercises/perfect-numbers/src/test/java/NaturalNumberTest.java)
[xkotlin](https://github.com/exercism/xkotlin/blob/master/exercises/perfect-numbers/src/test/kotlin/PerfectNumbersTest.kt)
[xlua](https://github.com/exercism/xlua/blob/master/exercises/perfect-numbers/perfect-numbers_spec.lua)
[xobjective-c](https://github.com/exercism/xobjective-c/blob/master/exercises/perfect-numbers/PerfectNumbersTest.m)
[xpython](https://github.com/exercism/xpython/blob/master/exercises/perfect-numbers/perfect_numbers_test.py)
[xracket](https://github.com/exercism/xracket/blob/master/exercises/perfect-numbers/perfect-numbers-test.rkt)
[xruby](https://github.com/exercism/xruby/blob/master/exercises/perfect-numbers/perfect_numbers_test.rb)
[xscala](https://github.com/exercism/xscala/blob/master/exercises/perfect-numbers/src/test/scala/PerfectNumbersTest.scala)
[xswift](https://github.com/exercism/xswift/blob/master/exercises/perfect-numbers/Tests/PerfectNumbersTests/PerfectNumbersTests.swift)

**Comment by petertseng** [comment]
That's pretty nifty that among the three consecutive numbers one each of abundant, deficient, perfect were represented. I wonder for how many sequences of consecutive 8-digit numbers this is true?

**Comment by stkent** [comment]
Observations:

- The vast majority of tracks require an implementation that identifies the classification (deficient/perfect/normal) of a number. Only a few tracks deviate from this (xelisp, xpython, xracket).
- Two tracks test for invalid input (xclojure, xkotlin).
- Many tracks do not test a non-prime deficient number.

Based on the range of values tested by existing implementations, I'm going to suggest the following tests in the following order for the canonical suite:

- Perfect: 6 (smallest), 28 (medium), 33550336 (large)
- Abundant: 12 (smallest), 30 (medium), 33550335 (large)
- Deficient: 2 (smallest prime), 4 (smallest non-prime), 32 (medium), 33550337 (large), 1 (edge case)
- Invalid (not whole numbers): 0 (non-negative integer), -1 (negative integer)

**Comment by stkent** [comment]
@petertseng exercise for the reader! 😉 Neat question though; feels very Project Euler-ish.

**Comment by petertseng** [comment]
I took a look at it, and the problem becomes slightly less interesting once one sees how many 8-digit perfect numbers there are (rot13(gung bar vf gur bayl bar)). I suppose one could expand the problem to not restrict oneself to 8-digit perfect numbers though...
