### ISSUE TITLE
saddle-points: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#582]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Saddle Points exercise can be found in the [./exercises/saddle-points/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/saddle-points for the up-to-date list of
language tracks that have an implementation of the Saddle Points exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/saddle-points

**Comment by stkent** [comment]
I'll tackle this soon.

**Comment by stkent** [comment]
xcsharp cases:

Readme example:
```
9 8 7
5 3 2
6 6 7
```

No saddle point:
```
2 1
1 2
```

Single saddle point, small matrix:
```
1 2
3 4
```

Single saddle point, large matrix
```
  18   3  39  19  91
  38  10   8  77 320
   3   4   8   6   7
```

Multiple saddle points:
```
4 5 4
3 5 5
1 5 4
```

**Comment by stkent** [comment]
xdelphi cases:

Same as xcsharp plus one extra:

Five-by-five:
```
34 21  61  41 25
14 42  60  14 31
54 45 [55] 42 23
33 15  61  31 35
21 52  63  13 23
```

**Comment by stkent** [comment]
xecmascript cases:

Same as xcsharp, minus readme example, plus a bunch of intermediate tests (checking that rows and columns can be extracted from a supplied matrix).

**Comment by stkent** [comment]
xelixir cases:

Same as xecmascript.

**Comment by stkent** [comment]
xfsharp cases:

Same as xcsharp.

**Comment by stkent** [comment]
xgo cases:

Same as xcsharp, minus readme example.

**Comment by stkent** [comment]
xhaskell cases:

Same as xcsharp.

**Comment by stkent** [comment]
xjavascript cases:

Same as xecmascript.

**Comment by stkent** [comment]
xperl5 cases:

Same as xecmascript.

**Comment by stkent** [comment]
xpython cases:

Tests readme example, plus:

Empty matrix (no saddle points).

No saddle point:
```
2 1
1 2
```

Multiple saddle points:
```
[5] 3 [5] 4
 6  4  7  3
[5] 1 [5] 3
```

Errors on invalid matrix:
```
3 2 1
0 1
2 1 0
```

**Comment by stkent** [comment]
xruby cases:

Same as xecmascript.

**Comment by stkent** [comment]
xscala cases:

Same as xpython, minus invalid input test.

**Comment by stkent** [comment]
xswift cases:

Same as xecmascript.

**Comment by stkent** [comment]
That completes the survey of existing tests; working on a PR with canonical data suggestions now!
