### ISSUE TITLE
word-search: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#591]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Word Search exercise can be found in the [./exercises/word-search/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/word-search for the up-to-date list of
language tracks that have an implementation of the Word Search exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/word-search

**Comment by stkent** [comment]
I'll tackle this soon.

**Comment by petertseng** [comment]
Is it the case that the C# and F# implementations deliberately test all eight directions?

If so, should that become the standard?

Does the existing example grid test all eight directions?

**Comment by stkent** [comment]
@petertseng I was just diving in to that, and yes: C# and F# test all directions, and C# (where I started reading) also checks a grid of a different size:

```
qwertyuiopz
luamsicrexe
abcdefghijk
```

**Comment by stkent** [comment]
C# also tests that words not in the puzzle are not found 👍

**Comment by stkent** [comment]
Ok, @petertseng, you nailed it: Go checks 4 of the 8 available directions.

E
S
W
NW

I'll use the updated version of the grid for the canonical tests.

**Comment by petertseng** [comment]
Perhaps the example grid can also get changed, then.

The other interesting corner case I would recommend is... literally the corner case. Check that a word is found even if one of its letters is in the bottom-right corner. Just checking those off-by-one errors.

**Comment by ErikSchierboom** [comment]
@stkent I'm not completely sure, but I think I copied the existing tests from the Python test suite, where I must have failed to regard the example data in the description. I do think that testing for all directions makes sense here, as that is also how one usually solves these puzzles. Having some corner cases is always good, so I'm all for that!

**Comment by stkent** [comment]
Here's a visualization of the current (newer) solutions. All corners are accounted for!

<img width="509" alt="screen shot 2017-02-28 at 9 27 27 pm" src="https://cloud.githubusercontent.com/assets/6463980/23443465/eb1c6820-fdfc-11e6-9a86-7e692409ba5a.png">

**Comment by stkent** [comment]
I opened a PR to update the description example: https://github.com/exercism/x-common/pull/617. I think the description could benefit from other refinements, but figured this was an easy change to make that might save someone from implementing the 'old' version while the canonical data is under construction :)
