### ISSUE TITLE
contributing guidelines: add PR recommendations

### ISSUE THREAD

**Issue by robphoenix** [exercism/x-common#596]
In https://github.com/exercism/xgo/pull/512 @kytrinyx made some good PR recommendations, specifically:

1.  the subject line in the PR to be a one-sentence summary. This is something that should not have the word *and* (explicitly or implied).
2. to have the detail in the body of the PR.
3. For things that are "closes #XXX" or "See #XXX" I prefer to have that in the body of the PR, simply because the subject line doesn't support markdown, and these don't get turned into links. It makes it harder to follow to go look at the related issue or PR.

If these are generally accepted recommendations across the tracks it would be good to include them in the contributing guide. Along with any other similar general preferences for PR's/Commit messages/Issues.

**Comment by behrtam** [comment]
You forgot the great link: https://chris.beams.io/posts/git-commit/

**Comment by robphoenix** [comment]
yes, of course!

**Comment by robphoenix** [comment]
closed by #598
