### ISSUE TITLE
Nonstandard `metadata.yml` properties

### ISSUE THREAD

**Issue by rbasso** [exercism/x-common#597]
A quick survey of `x-common/exercises/*/metadata.yml` files show that...

- 114 (all of them) have a `blurb` property.
- 86 have a `source` property.
- 82 have a `source_url` property.
- 7 have additional properties not listed above.

These are the 7 files with additional properties:

- [counter](https://github.com/exercism/x-common/blob/master/exercises/counter/metadata.yml)
- [error-handling](https://github.com/exercism/x-common/blob/master/exercises/error-handling/metadata.yml)
- [lens-person](https://github.com/exercism/x-common/blob/master/exercises/lens-person/metadata.yml)
- [nucleotide-codons](https://github.com/exercism/x-common/blob/master/exercises/nucleotide-codons/metadata.yml)
- [rectangles](https://github.com/exercism/x-common/blob/master/exercises/rectangles/metadata.yml)
- [react](https://github.com/exercism/x-common/blob/master/exercises/react/metadata.yml)
- [variable-length-quantity](https://github.com/exercism/x-common/blob/master/exercises/variable-length-quantity/metadata.yml)

All the atipical properties appear to be related to:

- exercise classification
- deprecation status

From what I understand, exercise classification became a track-specific
matter. Right?

The `counter` exercise is the only one that has a `deprecated` property,
while others - and also `counter` - have a `.deprecated` file, as described
in exercism/x-api#140:

- [count](https://github.com/exercism/x-common/blob/master/exercises/counter/.deprecated)
- [nucleotide-codons](https://github.com/exercism/x-common/blob/master/exercises/nucleotide-codons/.deprecated)
- [point-mutations](https://github.com/exercism/x-common/blob/master/exercises/point-mutations/.deprecated)

#### Is there any reason to keep these atipical properties in `metadata.yaml`?

My impression is that these properties are not serving any useful purpose
right now and should be deleted to avoid confusion, but I don't know if
there is code depending on these keys somewhere.

I'm also asking because, if the only useful properties are...

- `blurb`
- `source`
- `source_url`

... which are data pertaining the exercises - and not their status or
classification - it may be reasonable to consider merging this information
in `canonical-data.json`.

The resulting file would be mandatory, but the test cases would be optional.
There is a draft of this idea presented [here](https://github.com/exercism/x-common/issues/336#issuecomment-279666514).

**Comment by ErikSchierboom** [comment]
> From what I understand, exercise classification became a track-specific
matter. Right?

That is correct! In There was a [discussion](https://github.com/exercism/discussions/issues/60) first, and the end result was that each track had an issue opened for them. This is the issue for the F# track: https://github.com/exercism/xfsharp/issues/197. That means that any mention of topics in the metadata of exercises should be removed (not sure if any depends on them, but it seems unlikely).

> The counter exercise is the only one that has a deprecated property,
I think this is an error, as it should indeed be a `.deprecated` file.

**Comment by petertseng** [comment]
> `deprecated` property

Oh yeah, that was added in https://github.com/exercism/x-common/commit/8d48f5571fef67a1d47acd0a118457a265d2bc25 for #80 long before we had .deprecated files (https://github.com/exercism/x-api/pull/140)

I can tell you I find no uses of this property in https://github.com/exercism/trackler/search?utf8=%E2%9C%93&q=deprecated - the `deprecated` file is what is used.
