### ISSUE TITLE
phone-number: Does not properly specifiy test for numbers with length greater than 11

### ISSUE THREAD

**Issue by wolf99** [exercism/x-common#608]
The specification for the phone-number exercise says

> - If the phone number is more than 11 digits assume that it is a bad number

But the phone-number/canonical-data.json does not specify checking this properly. It checks for length of 11 without leading double 1 to be invalid and for length of 12 to be invalid. It should instead (according to the brief in the readme)check for any number greater than 11 to be invalid.

**Comment by tejasbubane** [comment]
@wolf99 If I understand correctly what you mean, the test for length 12 should suffice checking the case of greater than 11. Or maybe we need just one more testcase of arbitrary length greater than 11. What do others think? cc @rbasso @kotp

**Comment by rbasso** [comment]
@wolf99, maybe I got the idea, but I'm not sure. Could you clarify what exactly you want to be changed, preferable with the old and new json fragments?

**Comment by wolf99** [comment]
Current
```json
        {
          "description": "invalid when 12 digits",
          "property": "clean",
          "phrase": "321234567890",
          "expected": null
        },
```

New
```json
        {
          "description": "invalid when more than 11 digits",
          "property": "clean",
          "phrase": "321234567890",
          "expected": null
        },
```

The old version means that tests will check for implementations to use an input check similar to
 ```c
    if (length == 12) {
        return ERROR;
    }
```

When in fact it should be 
 ```c
    if (length > 11) {
        return ERROR;
    }
```

**Comment by tejasbubane** [comment]
> All lengths greater than 11 are invalid, not just lengths of 12.

Got it 😃  Nice catch! Would you mind sending a PR for this? Or else I can do the change.

**Comment by wolf99** [comment]
Added #719 then
