### ISSUE TITLE
clear description on pascals triangle

### ISSUE THREAD

**Issue by DeathSec** [exercism/x-common#609]
The pascals triangle exercise description is not explicit ,

Actual Mathematical Formula for finding pascals triangle( coefficient of Binomials)

Here P refers to Permutation => n!/(n-r)!
Here C refers to Combination => n! / (n-r)!r! , or , nPr / r!  

(x + a)^0 =  C(0,0) = 1
(x + a)^1 = C(1,0) , C(1,1) = 1  1
(x + a)^2 = C(2 , 0) , C(2 , 1) , C(2 , 2)  = 1 2 1

from above we can say , 
n row = C(n ,  0) , C(n , 0+1),   ..... C(n , n) 

i request that you change that, soon

**Comment by petertseng** [comment]
when I look at the current description: https://github.com/exercism/x-common/blob/master/exercises/pascals-triangle/description.md

It looks explicit enough to me.

There could still be a benefit for explaining it in terms of combinations. Would you please explain the benefits of doing so?

I would recommend that that explanation be in *addition* to what's currently there, not *replacing* it.

**Comment by DeathSec** [comment]
Just letting them know there are two possible solutions!.
