### ISSUE TITLE
run-length-encoding: How to deal with white spaces

### ISSUE THREAD

**Issue by behrtam** [exercism/x-common#613]
`<history>`
To understand how we got here I tried to figure out the history of the changes the happened to the run length encoding exercise.

In #238 the problem with numerical data for run length encoding input was raised and to keep the exercise simple it was decided to not include numbers.
This was "incorrectly" fixed in #530. Instead of excluding numbers, it reduced the input data range down to only upper case A-Z. There is no reason to exclude lower case characters and there was already test input data with white space, which is also totally fine.

This discrepancy between the new description and the old test data was discovered in #537. With #538 "only A-Z" was changed to include lower case and white spaces. But this change also introduced a new inconsistency because it assumed incorrectly that white spaces are left unchanged.
It is neither necessary to leave white spaces unchanged (there are some simple ciphers/encodings that relay on this), nor was it in accordance with the existing test data. 
`</history>`

*Status quo*: I also checked some language tracks (Python, Javascript, Ruby, Scala) and they all encode white spaces.

So, here is what I would like to propose we do ...

- [x] remove the part about "unchanged white space" from the description
- [x] close #610 

and maybe

- [x] add an explicit test case with lower case characters
- [x] add an explicit test case with white spaces

**Comment by DesHorsley** [comment]
Sounds good I'm happy to run with this if you'd like a hand.

**Comment by daveyarwood** [comment]
Good catch! I am on board with all of this, especially the explicit test cases for whitespace and lowercase characters.

**Comment by behrtam** [comment]
Okay, than lets get this ready to roll. @DesHorsley would you like to add the two test cases to the canonical test data? I would work on the description if no one else wants to do that.

**Comment by DesHorsley** [comment]
Sounds good

**Comment by robkeim** [comment]
Good detective work @behrtam to track this one down!

I like your proposed changes, although in #624 I don't see the description being updated for the exercise.

**Comment by kotp** [comment]
Thanks @behrtam and @robkeim and @DesHorsley
