### ISSUE TITLE
Word Count's Description Doesn't Mention Normalization

### ISSUE THREAD

**Issue by chrisguitarguy** [exercism/x-common#66]
[Word Count](https://github.com/exercism/x-common/blob/master/word-count.yml) doesn't mention that it expects the output to be normalized (all lower-cased), but it's expected:

- https://github.com/exercism/xgo/blob/1c5d360b98fc3a9f59c1e5e2f3a668ff8438419d/word-count/word_count_test.go#L38-L42
- https://github.com/exercism/xclojure/blob/171dc2068e196fc1e956ac702ca25aa50e5fe1a5/word-count/word_count_test.clj#L26-L28

**Comment by kytrinyx** [comment]
The README is just a high level description of the problem. The test suite defines the requirements. I don't know that it's necessary or even desirable to try to make the README reflect all the edge cases of a problem.

**Comment by chrisguitarguy** [comment]
Thought that might be the case, just wanted to see if it was. Thanks!

**Comment by kytrinyx** [comment]
Yepp, sure thing!
