### ISSUE TITLE
Move language-specific documentation into language-specific repositories

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#69]
At the moment the docs site (http://help.exercism.io) is a bit hard to use, and people don't really know to go there. Let's move all of the language-specific documentation into each language track repository.

We can create a `docs/` directory in the language repository (remember to add it as "ignored" in the config.json file).

Let's standardize on the following files (not all languages will have all sections):

- `ABOUT.md` - a friendly, conversational introduction about the language. What problems does it solve really well? What is it typically used for? Why should I learn it?
- `INSTALLATION.md` - should contain details about installing the language itself and any dependencies or configuration necessary to work on the exercises in that language.
- `TESTS.md` - should contain details about how to run the test suite for each exercise (described generically). Sometimes this will just be a single command, sometimes it will be more involved with instructions about a build system or how to do it via an IDE.
- `LEARNING.md` - If you're new to the language, what are some good resources to learn it from scratch?
- `RESOURCES.md` - links to useful resources on the web or elsewhere.

The problems API can deliver documentation as easily as test suites and READMEs. We could add a simple `/docs/:language` endpoint to [x-api](https://github.com/exercism/x-api) that serves up this content in its separate sections.

This can then be consumed by the language landing pages that are being planned for the exercism.io site itself (discussion: https://github.com/exercism/exercism.io/issues/2299).

Also, we can use this for the track-level README:

- API issue - https://github.com/exercism/x-api/issues/31
- Original issue - https://github.com/exercism/exercism.io/issues/1931

Later, we can add more files to this directory (e.g. CONTRIBUTING.md for ways in which you can contribute to that language track).

Thoughts? Counter-suggestions? Objections?

**Comment by Dog** [comment]
I think this is a good idea.

**Comment by groyoh** [comment]
@kytrinyx  I'm going to start to work on some docs migration. Some of them (like https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-csharp.md) use images, how should they be handled?

**Comment by groyoh** [comment]
According to @kytrinyx comment [here](https://github.com/exercism/xpython/pull/176#issuecomment-98294773), images should be `docs/img`.

**Comment by groyoh** [comment]
Taks list up to date:
- [x] https://github.com/exercism/xclojure
- [x] https://github.com/exercism/xcoffeescript
- [x] https://github.com/exercism/xcpp
- [ ] https://github.com/exercism/xcsharp
- [ ] https://github.com/exercism/xelixir
- [ ] https://github.com/exercism/xerlang
- [ ] https://github.com/exercism/xfsharp
- [x] https://github.com/exercism/xgo
- [x] https://github.com/exercism/xhaskell
- [x] https://github.com/exercism/xjava
- [ ] https://github.com/exercism/xjavascript
- [ ] https://github.com/exercism/xlisp
- [ ] https://github.com/exercism/xlua
- [ ] https://github.com/exercism/xobjective-c
- [ ] https://github.com/exercism/xocaml
- [ ] https://github.com/exercism/xperl5
- [x] https://github.com/exercism/xphp
- [ ] https://github.com/exercism/xplsql
- [x] https://github.com/exercism/xpython
- [x] https://github.com/exercism/xruby
- [x] https://github.com/exercism/xscala
- [ ] https://github.com/exercism/xscheme
- [x] https://github.com/exercism/xswift

**Comment by kytrinyx** [comment]
Awesome, thanks for working on this!

**Comment by groyoh** [comment]
A pleasure to help! :smile:

**Comment by groyoh** [comment]
All the docs have been added to the language repos :smile:

**Comment by groyoh** [comment]
@kytrinyx The documentation have been moved for all repositories that are on the help site. What about about the ones that are not documented?

**Comment by kytrinyx** [comment]
I only listed the active languages... if we have documentation for inactive languages I would love to get those moved as well.

**Comment by kytrinyx** [comment]
This is now done. For languages that are not yet active, we'll check this before we flip the switch.
