### ISSUE TITLE
bracket-push: curious: why do you suppose it's called bracket-PUSH?

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#693]
The [bracket-push exercise](https://github.com/exercism/x-common/tree/master/exercises/bracket-push) is about determining whether the brackets in a given string are balanced.

So, one asks, why is the word "push" in the slug? I didn't see an explanation in https://github.com/exercism/xjavascript/pull/31 where the exercise was added. Why is the exercise not called `bracket-matching` or `brackets` or something similar?

Well, okay, I can guess why: The name is meant to hint to the students that we can use a stack, because stacks have the "push" operation in the traditional literature. *Aside: I wonder why that is so? I found http://stackoverflow.com/questions/420315/stacks-why-push-and-pop that may explain it*.

In that case, I will half-jokingly note that this exercise name unfairly biases the solution space toward solutions that explicitly use a stack data structure and away from solutions using:

* recursive-descent parsers (well hey, the function call stack is, too, a stack!)
* some sort of state machine using the same grammar as the recursive-descent parser. Note that I can't really say "finite automaton" here (whether it be deterministic or not) because the language of nested brackets is not finite. But something similar, perhaps? Though of course its internal state will probably also be a stack of some sort.
* Iteratively attempting to remove any innermost pair of brackets until you can no longer do so. No stacks in this solution at all.

Now, remember that it is our [policy](https://github.com/exercism/discussions/issues?q=is%3Aissue+label%3Apolicy+is%3Aclosed) that [our exercises should not drive students toward any particular implementation](https://github.com/exercism/discussions/issues/41).

Since the name bracket-push does so, I considered proposing that we [rename it](https://github.com/exercism/discussions/issues/12).

Unfortunately, this is not my battle to fight today. But hey, if anyone ever comes along and makes the same proposal, you could let the proposer know that I agree, yeah?

**Comment by petertseng** [comment]
I do not need a response. Have a nice day. (Or give your guess as to why it's called bracket-push)

**Comment by petertseng** [comment]
Small correction: 

> I can't really say "finite automaton" here (whether it be deterministic or not) because the language of nested brackets is not finite.

Right statement, wrong reason. An infinite language can be accepted by a finite automaton if it is regular. It is better to say "the language of nested brackets is not **regular**"

**Comment by petertseng** [comment]
> some sort of state machine using the same grammar as the recursive-descent parser

I have just found out that such a state machine might be called... a **push**down automaton...!!!

This lends its credence to the name of the exercise!

**Comment by rbasso** [comment]
The name makes sense, but it kind of suggests a solution instead of posing a problem.

See: exercism/discussions#124.
