### ISSUE TITLE
tournament: should reject inputs containing invalid lines

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#720]
The tournament exercise currently asks the implementation to silently [ignore invalid lines](https://github.com/exercism/x-common/pull/299).

I would say it is not good design for an API to silently ignore invalid inputs, as that may produce surprising results for users of that API.

It seems more helpful to have inputs containing invalid lines to be rejected (in whatever way is appropriate for the target language).

My recommendation is:

* change the [description](https://github.com/exercism/x-common/blob/master/exercises/tournament/description.md) to state that input with invalid lines are rejected.
* change the [cases in the canonical data](https://github.com/exercism/x-common/blob/master/exercises/tournament/canonical-data.json) to expect errors for inputs with invalid lines.
  * I suggest that each test case contain only one invalid line, so that we can be sure that each individual invalid line is rejected. If a test case contained multiple invalid lines we might not be sure that an implementation would reject all invalid lines in that single case.

**Comment by rbasso** [comment]
Considering that we just changed the test data in #717, adding a test case for invalid data, but also removing some more detailed information about the meaning of each type of invalid line, I am linking here the [latest version of the file before the change](https://github.com/exercism/x-common/blob/04905ab9455417b0bfb610350bf4c264494e4326/exercises/tournament/canonical-data.json), for convenience.

The information may be needed to generate the new test cases rejecting invalid data.

**Comment by Insti** [comment]
Alternatively, only have test cases that contain valid lines.

This exercise is about parsing a specified format and converting it into a pretty table, it is not a general string parsing problem.

**Comment by petertseng** [comment]
I thought about it. No complaints here. I'll see if there are any before officially changing the recommendation in the issue title.

To be clear, to me:

"Do not test invalid inputs" is only *slightly* preferred to "Test that invalid inputs are rejected", and both of those are **strongly** preferred to "Test that invalid inputs are ignored".
