### ISSUE TITLE
Consistent naming of properties that return boolean value

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/x-common#733]
While working on writing test generators based on the canonical data, I noticed a small inconsistency. The [isogram canonical-data](https://github.com/exercism/x-common/blob/master/exercises/isogram/canonical-data.json)  has named its property `isIsogram`, which makes for a nice, readable function name. However, the [leap canonical-data](https://github.com/exercism/x-common/blob/master/exercises/leap/canonical-data.json) has named its property `leapYear`, which makes for a slightly less readable function name. I would much prefer to use `isLeapYear`, which looks clearer to me. 

Of course, I could modify my test generator to prepend the "is" part, but maybe we should strive to standardize the naming for boolean properties?

**Comment by rbasso** [comment]
I also prefer `isLeapYear`, @ErikSchierboom, but I think that naming conventions have a lot to do with the language and personal preferences, so I'm not sure if it is worthy a *tabs vs spaces* war to standardize it (two spaces using Vim, of course 😄 ).

Anyway, I'll list some alternatives that conform to the schema as a conversation starter, so that we can see if it is contentious:

- leap
- leapYear
- IsLeap
- isLeapYear
- isBissextileYear
- isAnIntercalaryYearInTheGregorianCalendar
- f

**Comment by ErikSchierboom** [comment]
My vote goes to: `isLeapYear`, which is think best communicates what we expect the function that implements it to do.

**Comment by jtigger** [comment]
@rbasso said:
> two spaces using Vim, of course

I knew you were a right-thinking person. ;)

**Comment by petertseng** [comment]
We can use a standard here if it will help comprehension. If a test generator is able to figure things out from seeing that `expected` is of type boolean, then great. If some language's test generators need a small exercise-specific portion, then the consistency might help the implementor.

I acknowledge that languages will want to use different names for their functions, such as `is_leap_year` or `leap?` or `leap-p` (there *is* some language that does this, right? I could have sworn there was...). Note that is true no matter what name x-common chooses.

**Comment by petertseng** [comment]
EBWODP: It's `leapp`, not `leap-p`. No hyphen if the name does not contain any other hyphen.

**Comment by hilary** [comment]
"naming conventions have a lot to do with the language" 👍 

As either way we decide, some languages will end up preprocessing the resulting names, maybe we should figure out how many languages use each convention?

Ruby's naming convention is to use '?' and not a prefix.

**Comment by ErikSchierboom** [comment]
So would having a standard here help or is the benefit not great enough? I'm not entirely sure if the benefit is great enough.

**Comment by behrtam** [comment]
I think we should have a standard so that they all look the same. I would vote for `isLeapYear`.

**Comment by Insti** [comment]
Does this also make sense for:

`luhn`: `valid`, 
`custom-set` : `equal`
`clock` : `equal`
`queen-attack` : `canAttack`
`dominoes` : `canChain`,
`triangle` : `equilateral`, `isosceles`, `scalene`

`canAttack` might still be a better name than `isAttackable` or `isChainable`

Perhaps this would make a better guideline than a strict rule?

**Comment by ErikSchierboom** [comment]
@Insti I think that would be best,

**Comment by ErikSchierboom** [comment]
Okay. Let's close this issue and just remember to keep an eye out for possibly non-optimal boolean properties.
