### ISSUE TITLE
wordy: clarify README

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#74]
In https://github.com/exercism/xruby/issues/116 @dalexj correctly points out that there is an operation that is either blatantly wrong, or the instructions are too ambiguous.

```plain
What is -3 plus 7 multiplied by -2?
=> -8
```

By the usual rules of order of operations, that should be -17.

When I was in primary school we would be asked to solve word problems out loud, and the adult would say it like this: _What is -3 plus 7 <pause> multiplied by -2?_, clarifying that the order of operations was always to be taken left to right.

When the word problems are written down, however, this is not necessarily the obvious choice.

Should we clarify the README to say that order of operations is left-to-right? Or should we fix the answer to reflect the correct order of operations?

**Comment by Dog** [comment]
I'd favor order of operations going from left to right for this problem. I think when people say a word problem, they aren't expecting the other person to reorder their words for the order of operations. I think they are expecting them to accumulate the total over the course of the problem, considering each step of the problem as it is given.

**Comment by kytrinyx** [comment]
I also favour left-to-right. I'll leave this open for a couple more days in case others have an opinion.

**Comment by kytrinyx** [comment]
Conclusion: Let's fix the README in the wordy problem to clarify that the order of operations is left-to-right.

**Comment by IanWhitney** [comment]
Did this get closed by #233?

**Comment by IanWhitney** [comment]
I'm pretty sure it did. Closing for now. Someone else can re-open if I'm totally off base.
