### ISSUE TITLE
README references nonexistent `doc/` directory

### ISSUE THREAD

**Issue by petertseng** [exercism/x-common#768]
Quoth the [README](https://github.com/exercism/x-common/blob/master/README.md):

> The `doc/` subdirectory contains all documentation that is not specific to a language 

This directory does not exist and has never existed since https://github.com/exercism/x-common/commit/967c55ae60145e4d4f10ab467337d0064b287b48 nor https://github.com/exercism/x-common/commit/08b78764536ad28f4ad8434dad5dbdc99b3ae78f.

So, the line should be deleted.

If there is any relevant information that was in those docs, that line can be replaced with an appropriate link. Perhaps it will be https://github.com/exercism/docs . If suggesting a replacement, let's take into account the appropriateness of placing the replacement link in the introductory sentence of this repo.

Unless there is a suggestion, let's assume there is no replacement necessary. This sentence can/should be updated with the latest recommendation.

**Comment by morrme** [comment]
I'm happy to remove the line and/or replace as needed. Has there been a consensus?

**Comment by petertseng** [comment]
The thumbs ups give evidence that two people other than myself saw this and accepted the suggestion of "no replacement".
