### ISSUE TITLE
difference-of-squares: add 0 test cases

### ISSUE THREAD

**Issue by weibeld** [exercism/x-common#789]
I propose to add the test cases `"square of sum 0"` and `"sum of squares 0"` to the test suite. In this way, the edge case of 0 would be tested properly.

For `"difference of squares"` the 0 input is tested, but not for `"square of sum"` and `"sum of squares"`. So, I think it should be the same for all three cases.

**Comment by Insti** [comment]
If you're not making a PR that already has it, it is useful to link to the thing you are referring to. In this case the difference-of-squares canonical data: https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/canonical-data.json
and description: https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/description.md

**Comment by weibeld** [comment]
Ok, I will make a PR 👍

**Comment by petertseng** [comment]
Looks like we decided on 1 instead of 0 in #791.
