### ISSUE TITLE
Getting the latest version of a problem?

### ISSUE THREAD

**Issue by derifatives** [exercism/x-common#792]
I'm doing the Haskell track. I seem to have fetched an old version of luhn. In particular, `exercism fetch haskell luhn` seems to be pull the [March 14 version](https://github.com/exercism/xhaskell/commit/276f86fd1c2415ed0a044881649a22897f7d4b0d) rather than the latest version, and I'm not sure why. I *think* I just downloaded it today for the first time, although I could be wrong. My exercism is client is 2.4.0.

I've searched the docs a bit but not found any info on this. My apologies for the (likely) case where I've missed something obvious.

Any thoughts?

**Comment by petertseng** [comment]
It is true that you're missing something, but the something you're missing is rather non-obvious.

I see from https://github.com/exercism/trackler/tree/master/tracks that the current version of the Haskell track being served by the site is https://github.com/exercism/xhaskell/tree/381d33942c62bcad6dbbba56a0ae373e1b2f69c5 . Importantly for this issue, https://github.com/exercism/xhaskell/pull/533 had not been merged at that point.

**Comment by petertseng** [comment]
There are actually more places to look than what I just described, but the above was sufficient.

http://x.exercism.io/ says that the currently-deployed revision of x-api is ef21b10. then, https://github.com/exercism/x-api/blob/ef21b1028639cb801e1c03e737d2b7575ceda021/Gemfile.lock tells us that trackler was at 2.1.0.11 at the time. Then we see that 2.1.0.11 is in fact the latest version of Trackler, so then what I said above applies.

**Comment by petertseng** [comment]
Now obviously I've only described why this is happening, and not how to get the latest version of a problem (issue title). I am aware of a few solutions, listed in the order I would attempt them:

* Acquire the relevant files from track's repo
* Wait an unknown period of time for the next deploy
* Run an instance of the x-api server with a modified trackler gem, edit your exercism config to point your exercism binary at the local server, and then `exercism fetch` will acquire the corresponding files. Resources that may help in achieving this:
    * https://github.com/exercism/xjava/blob/master/bin/journey-test.sh
    * https://github.com/exercism/xkotlin/blob/master/bin/journey-test.sh
    * https://github.com/exercism/xerlang/blob/master/bin/journey-test.sh

**Comment by petertseng** [comment]
> Wait an unknown period of time for the next deploy

The unknown period of time has passed for this instance (though it is still unknown in the general case). The demonstration of this fact can be had at http://x.exercism.io/v2/exercises/haskell/luhn

**Comment by petertseng** [comment]
In case it is of interest, for me what I do to get notified of a deploy is I'm in the exercism/dev channel in gitter, so I see messages like

```
14:08:53 <           gitter> Heroku [exercism] deployed b782477
```

it's now 16:44 my time so that was about 2.5 hours ago

**Comment by petertseng** [comment]
We are ready to close this now. The reason is that in the short term, the deploy happened so that `exercism fetch` will fetch the newest version of the exercise. A file that already exists will not be overwritten (see https://github.com/exercism/cli/issues/362 for that), so any file that wants to be overwritten should be removed, then `exercism fetch` will write it afresh.

In the long term, we can see a discussion about more automation in the submodule updates at https://github.com/exercism/x-api/issues/114 and make an issue at https://github.com/exercism/trackler for further discussion of that
