### ISSUE TITLE
404 urls in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tleen** [exercism/x-common#796]
Under the section "[Improving Consistency By Extracting Shared Test Data](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data)", the first two links "this issue" and "list of open todos" point to URLs that no longer exist.

**Comment by kytrinyx** [comment]
Thanks @tleen. I need to delete a bunch of stuff from the contributing guide, now that we're documenting everything in the https://github.com/exercism/docs repo.

I'll do that today.

**Comment by stkent** [comment]
Closed by #797.
