### ISSUE TITLE
clock: first two description lines are near-dupes

### ISSUE THREAD

**Issue by stkent** [exercism/x-common#813]
The [description for the exercise `clock`](https://github.com/exercism/x-common/blob/master/exercises/clock/description.md) begins:

> Implement a clock that handles times without dates.
>
> Create a clock that is independent of date.
>
> ...

Since these lines are so similar, we should cherry-pick the best parts to form a single introductory sentence, then update the exercise metadata to use that sentence for the [blurb](https://github.com/exercism/x-common/blob/master/exercises/clock/metadata.yml) also.

**Comment by Insti** [comment]
Please review and/or merge https://github.com/exercism/x-common/pull/802

**Comment by Insti** [comment]
Thanks @stkent 

Resolved by: #802
