### ISSUE TITLE
Scrabble-score: 'multibillionaire' is too long for an actual scrabble board

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#86]
Even though most of the problems don't deal with validation of inputs etc, it still seems like a good idea to use words that might actually occur in a scrabble game, if only because it's less distracting.

**Comment by kotp** [comment]
Mr. Butts should be rolling in his grave.

Going to look at this in the repository, but will leave his grave alone, as I don't really want to find out.

Should we replace that word with something more appropriate, such as 'oxyphenbutazone'?

**Comment by kytrinyx** [comment]
Works for me :)

**Comment by petertseng** [comment]
it seems to me like this would be a great opportunity to get common inputs/outputs in a json file

**Comment by petertseng** [comment]
it seems to me like this would be a great opportunity to get common inputs/outputs in a json file

Edit: Oh, I see, it is already in progress https://github.com/exercism/x-common/pull/161

**Comment by drewbs** [comment]
This issue can be closed once the following PR's have been merged: 

- [exercism/xcpp#75](https://github.com/exercism/xcpp/issues/75)
- [exercism/xperl5#113](https://github.com/exercism/xperl5/issues/113)
- [exercism/xperl6#27](https://github.com/exercism/xperl6/issues/27)

Thanks

**Comment by kytrinyx** [comment]
Thanks @drewbs!

**Comment by drewbs** [comment]
Thanks @kytrinyx for implementing the changes!
