### ISSUE TITLE
"Hello, World!" spec and implemented problems are inconsistent with the traditional output

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#87]
The spec currently says `Hello, world!`, whereas the traditional output is `Hello, World!` (capitalized `W`).

http://en.wikipedia.org/wiki/%22Hello,_World!%22_program

We should fix both the spec and the individual problems across the board.

If you're fairly new to programming, open source, or exercism, there's some context about this feature here: https://github.com/exercism/rossconf/issues/12 and here: https://github.com/exercism/rossconf/issues/2

Also: ask questions if anything is unclear, I'd love to fix any sort of documentation to make it easier to get started contributing to exercism.

**Comment by skeskali** [comment]
I'm very new to open source but would like to contribute. Is it as simple as correcting the hello-world.yml file? Or is this found in other files throughout the repository?

**Comment by kytrinyx** [comment]
Hi! Thanks so much for jumping in here.

There are going to be two possible places in this repository to make the fix:

- `hello-world.yml`
- `hello-world.md`

If you're feeling up to some spelunking and experimentation, there's a second step to this, and that is to update the test suite and example solution for individual implementations of the problem (e.g. the ruby version, and/or the scheme version).

Here's the list of languages that has this problem:

http://x.exercism.io/problems/hello-world

(look at the value for the key "track_ids")

For each language, the corresponding repository will be at: "https://github.com/exercism/x{TRACK_ID}", so for example ruby will be at https://github.com/exercism/xruby and Lua will be at https://github.com/exercism/xlua

Working on problems in languages that you don't know can be daunting, so do not feel obliged to tackle those.

**Comment by skeskali** [comment]
I'm definitely up for the challenge of the second step, but it looks as though all of the languages listed here (http://x.exercism.io/problems/hello-world) have been spoken for. No one's actually called dibs on scala and scheme, but there are check marks next to the repos in the list. Am I reading that right, or do the check marks have some other meaning?

**Comment by kytrinyx** [comment]
The check-marks mean that the hello-world exercise was implemented, but they were implemented against the old spec (not capitalized "world"), so this issue is about fixing that in the existing implementations.

**Comment by kotp** [comment]
According to that Wikipedia link, the traditional has been lowercase 'w', including the original.  And it is proper in the sense that 'world' is not a name.  The only place in the entire article where a capital letter is used conversationally, is likely (afaict) a typographical error.  This includes the "First Known Use" example as given, which would likely be the most traditional of any use.

I am not saying to _not_ make the change, and to do so consistently (which may be the only purpose of this issue and one I cheer for!), only that "Hello world." is perfect as a sentence.  and traditionally, it has not been used for its grammatical perfection (often used without punctuation) and I think applicable in any sense that is "good enough" to demonstrate an example.

I also think that capitalizing 'World" hints at capitalizing what is given as an argument to the method, which may be the wrong thing to do.  Perhaps ironically, I hope this *does* happen, though, as it fosters exploration and discussion.

**Comment by kytrinyx** [comment]
> I also think that capitalizing 'World" hints at capitalizing what is given as an argument to the method

That never occurred to me, and I would definitely push back on that. Not everyone capitalizes their name, for one. Also, you could pass in things that are not names, but which are correct in terms of the problem. "Hello, people of Earth!"

**Comment by kotp** [comment]
Right.  There are plenty of applications that slaughter my name.  

I think the lower case world indeed shows that it is not a 'feature' sought after for how to manipulate the string, just simply a 'sanity check' as intended traditionally.

**Comment by kytrinyx** [comment]
The input matches the output, so there's nothing that suggests string manipulation, in my opinion, regardless of case.

**Comment by kotp** [comment]
The capitalized "World" is not any different than Alice or Bob, as proper names.  The lower case name solidifies that there is no such thing as the "capitalized argument" requirement.  It is the thing that shows the "edge case" of not having that proper name.  The empty string simply does not do this.

Should we run a nitpick test on this exercise?  See what happens if a few submitters are asked "What about saying hello to a strange cat?"  This will help ensure there is not a name, just the generic applied, without prompting for an answer?

**Comment by kotp** [comment]
Though I do want to say I understand that the current tests simply match the input.  The output will always be the same.

So should we test that it is not being enforced?  A test that reads something like:


```ruby
def test_hello_strange_cat
  skip
  refute_equal 'Hello, kitten!', HelloWorld.hello('Kitten'), 'Given a kitten, we do not greet Kitten."'
end
```

**Comment by kytrinyx** [comment]
I don't think so. The hello world exercise is really just a wiring exercise. If we want to have an exercise that has to do with [respecting people's names](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/), then I think we should make a separate exercise.

The hello world exercise will not be nitpicked.

**Comment by kotp** [comment]
Sounds great to me.

**Comment by kytrinyx** [comment]
OK, cool.

Thanks for discussing, I'm going to go ahead and close this.
