### ISSUE TITLE
queen-attack might be missing test cases

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#89]
See https://github.com/exercism/xcpp/pull/42

In some tracks only one diagonal was tested. It could be worth checking other tracks, and perhaps extracting the test cases into a `queen-attack.json` file.

**Comment by IanWhitney** [comment]
@kytrinyx, With the standard tests merged I think this one is done!

**Comment by kytrinyx** [comment]
w00t! Thank you :)
