### ISSUE TITLE
Improve test inputs for 'binary'

### ISSUE THREAD

**Issue by kytrinyx** [exercism/x-common#95]
In https://github.com/exercism/exercism.io/issues/2425

@odeits suggests adding the edge case `"10convert01"`. We could also split it up into `10convert` and `convert10`.

**Comment by kotp** [comment]
Can Ruby be marked complete due to exercism/xruby#171

**Comment by kytrinyx** [comment]
Done.

**Comment by kotp** [comment]
Consistency as noted in exercism/xruby/issues/174 should be addressed.

How many of these invalid are exception based, rather than 0 based?

**Comment by kytrinyx** [comment]
I'm not sure--but I'd like to just change the README to allow for both approaches.

**Comment by kotp** [comment]
You beat me to it. :)

**Comment by NobbZ** [comment]
I#ve just stumbled over a solution in the elixir track which would "convert" the string "22" to ``2 * 1 + 2 * 2 = 6``, probably we should not only have invalid tests with alphabetic characters but numeric chars also.

**Comment by kytrinyx** [comment]
Ah, yes, that's a good catch.

**Comment by NobbZ** [comment]
I'd be very happy if we get some common test data before fixing this issue. Fixing it now per track and collecting common test data afterwards and then file an issue per track again might create additional and unnecessary noise in the tracks repositories and additional confusion on commenting submissions that are against different versions of the tests.

**Comment by NobbZ** [comment]
Since we are in the process of deprecating `binary` along other exercises in a big sweep (exercism/x-common#279), I think we can close this, can't we?

**Comment by kytrinyx** [comment]
Yeah, I think we can. Thanks!
